### ISSUE TITLE
Unhandled exception thrown after ping timeout

### ISSUE THREAD

**Issue by thomastanck** [sopel-irc/sopel#1010]
exceptions.log

```
Critical exception in coreTraceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sopel/__init__.py", line 66, in run
    p.run(config.core.host, int(config.core.port))
  File "/usr/local/lib/python2.7/site-packages/sopel/irc.py", line 154, in run
    self.initiate_connect(host, port)
  File "/usr/local/lib/python2.7/site-packages/sopel/irc.py", line 173, in initiate_connect
    asyncore.loop()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
```

stdio.log

```
Could not open CA certificates file. SSL will not work properly.

Welcome to Sopel. Loading modules...




Registered 4 modules,
0 modules failed to load


Connecting to irc.ppy.sh:6667...
Connected.
Ping timeout reached after 120 seconds, closing connection
Calling shutdown for 0 modules.
Closed!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sopel/__init__.py", line 66, in run
    p.run(config.core.host, int(config.core.port))
  File "/usr/local/lib/python2.7/site-packages/sopel/irc.py", line 154, in run
    self.initiate_connect(host, port)
  File "/usr/local/lib/python2.7/site-packages/sopel/irc.py", line 173, in initiate_connect
    asyncore.loop()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
```

I've been trying to figure out why this happens, but I have no idea really

**Comment by maxpowa** [comment]
Apparently this issue only effects OS X users. 

Modify /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py and set the default of `use_poll` from `False` to `True`:

Line 207:
```python
def loop(timeout=30.0, use_poll=False, map=None, count=None):
``` 
to
```python
def loop(timeout=30.0, use_poll=True, map=None, count=None):
```

http://stackoverflow.com/a/1094626

Solution is pulled pretty much directly from the StackOverflow answer, so YMMV

**Comment by elad661** [comment]
@maxpowa this stackoverflow link doesn't seem relevant. I think you pasted the wrong link. 

Anyway, we can definitely disable use_poll on specific platforms if this actually solves the problem, but I'm reluctant to make changes I can't test. Since I don't have access to any OS X device, I can't test this myself.

@thomastanck can you please try to edit sope/irc.py and change line 173 from `asyncore.loop()` to

```python
use_poll=False
if sys.platform == "darwin":
    use_poll=True
asyncore.loop(use_poll=use_poll)
```

and test to see if this fixes the problem? If it does, I'll commit this to master, if it doesn't we'll need to investigate this issue some more.

**Comment by maxpowa** [comment]
@elad661 Whoops! It was missing a trailing 1.

**Comment by thomastanck** [comment]
No, after I posted this issue, this bug hasn't appeared at all, which is strange. I don't want to make a modification without knowing it doesn't work as it is...

```
Welcome to Sopel. Loading modules...




Registered 4 modules,
0 modules failed to load


Connecting to irc.ppy.sh:6667...
Connected.
Calling shutdown for 0 modules.
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...

Welcome to Sopel. Loading modules...




Registered 4 modules,
0 modules failed to load


Connecting to irc.ppy.sh:6667...
Connected.
```

I'm getting loads of these now and it's been running for a week already

**Comment by elad661** [comment]
I think a disconnection is a different code path than ping timeout, in this case. In the case of disconnection, asyncore's loop stops by itself (ie. if the TCP connection dies) and then we call the cleanup stuff and start again.

But on a ping timeout, asyncore didn't notice the connection died - the socket might still be open and the TCP connectionis probably still alive, but our ping timeout monitoring thread noticed we didn't see any incoming application-level activity (such as messages or replies to our PING queries) on the connection for a while, so we *tell* asyncore to stop the loop, and then it stops and the cleanup stuff is called and we start again.

So I think it's safe to say this bug is still there.

According to some cursory google searching, it seems that this issue happens on OS X when we tell the asyncore loop to quit from a different thread, which sounds like it fits our usecase with the ping timeout monitoring which runs on a different thread than the main loop.

Telling asyncore to use `poll()` instead of `select()` will probably not cause any noticeable difference in Sopel's behaviour (other than not triggering this bug), because it's a small app... it's not like a webserver serving a lot of concurrent connections, where these choices really matter.

Since the ping timeout checker merely calls `handle_close()`, you can probably trigger this bug by adding a module command that calls `bot.handle_close()` directly, which would cause the connection to end as if the ping timeout handler noticed a timeout... this should, in theory, trigger the bug...

Of course you don't have to test this with your production bot - you can run multiple instances of sopel with different config files on the same machine.

**Comment by working-name** [comment]
Still an issue on OS X

I'm not sure how to help debug this, but I'm willing to do whatever.

```
Ping timeout reached after 120 seconds, closing connection
Calling shutdown for 0 modules.
Closed!
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/sopel/__init__.py", line 79, in run
    p.run(config.core.host, int(config.core.port))
  File "/Library/Python/2.7/site-packages/sopel/irc.py", line 154, in run
    self.initiate_connect(host, port)
  File "/Library/Python/2.7/site-packages/sopel/irc.py", line 173, in initiate_connect
    asyncore.loop()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/asyncore.py", line 145, in poll
    r, w, e = select.select(r, w, e, timeout)
error: (9, 'Bad file descriptor')
```

I made the aforementioned change in irc.py, will report back if the next timeout causes sopel to exit completely.

**Comment by maxpowa** [comment]
@working-name It appears your issue after the `use_poll` change is just your network timing out, are you connecting from a potentially unstable connection (2G/3G/LTE/WiFi/etc)?

**Comment by working-name** [comment]
@maxpowa It's a wired box, [business cable ISP](https://youtu.be/0ilMx7k7mso). I wouldn't call it stable, but since the pattern seems the same to me I assumed the issue persists. I have run eggdrop, and phergie before on the box, and I don't remember it dropping so much.

**Comment by maxpowa** [comment]
@working-name Out of curiosity, which version of OS X are you using?

**Comment by working-name** [comment]
Yosemite, 10.10.3

**Comment by maxpowa** [comment]
And in your config, you haven't defined `timeout` under the core section, correct?

**Comment by working-name** [comment]
I'm sorry, that's 10.11.2 for that particular machine, and timeout is not defined in core.

**Comment by working-name** [comment]
However, if it is simply timing out, what's the point of quitting the process rather than simply reconnecting to the network?

**Comment by dgw** [comment]
If no one can reproduce this and provide more info by the time **7.0.0** is ready, I'm going to close this.

Assigning milestone as a reminder.

**Comment by dgw** [comment]
Gonna close this out. So much of the connection-handling has been rewritten that none of the logs or errors in this issue are of use any more. Also, since there has been no further info added to this issue in nearly three years… Let's start over if/when someone finds a similar issue in the current code on `master`.
