### ISSUE TITLE
[url] meaning of `exclude` changed?

### ISSUE THREAD

**Issue by anarcat** [sopel-irc/sopel#1032]
i used to have the following in my `sopel.cfg`:

``` ini
[url]
exclude =
exclusion_char = !
```

... and it worked fine up to (and including) 6.1.1. After an upgrade to 6.3.0, the bot was silent on `.title http://example.com/`, all of a sudden - the above`exclude` pattern would match everything!

after removing the above block, the proper `.title` behavior was restored. the problem is the above is the default config generated when you run `sopel -w`: so by default, now, it seems that the url plugin config is basically broken and there's no way to configure the bot to _not_ be silent (unless you input an impossible regex) by default.

**Comment by dgw** [comment]
Spent some time working on this. Apparently this config section:

````ini
[url]
exclude = 
exclusion_char = ^
````

causes the URL exclusions list to contain a single empty string, which `setup()` tries to compile. In debugging different pieces of the module I've variously caused the module to spit out an error, fail to load, and even crash the whole bot on reload. At any rate, a regex with the pattern `''` will match any URL, which effectively makes it exclude any link, which is bad.

What I haven't been able to do is cleanly prevent `url.setup()` from compiling `''` as an exclusion regex. One would think that tweaking the relevant part of `setup` to read:

````python
    if bot.config.url.exclude:
        regexes = [re.compile(s) for s in bot.config.url.exclude if s]
````

would prevent it, because `''` evaluates to `False` in conditionals. I also tried `if s != ''`, with no luck. I even did some interactive console investigations to confirm that, and it does what it should in a trivial Python console example:

````
>>> import re
>>> r = ['']
>>> len(r)
1
>>> len([re.compile(s) for s in r if s])
0
````

But if I did things I shouldn't do and used `bot.say()` in `setup()` to print out `' '.join([hex(ord(c)) for c in s])` for each exclusion rule during module reload, it said simply `<sopel> excluded url pattern: `.

I eventually had to give up simply due to fatigue (I did this last night, after midnight). It's just strange, something that seems from all accounts like it _should_ work, not working.

**Comment by dgw** [comment]
Was trying to test the proposed changes in #1244, and ran across this again because my config still had `^` as the exclusion character.

First of all, `exclusion_char = \^` (escaped) works for me, but it doesn't work without the `\`. Interpolating special characters into regex seems error-prone. But `core.prefix` requires escaping too, so... sigh. It's not likely to change until a major version (7.0.0) if ever.

Deleting `exclude` from the `[url]` section entirely works. But an empty property doesn't work, so that's the bug with the `exclude` config setting.

I'm playing with one way of fixing this, which I found just now. @anarcat, can you test out 4afb421 and see if it fixes your issue with `exclude = ` (empty)?

**Comment by anarcat** [comment]
sorry, i don't have time to followup on this right now unfortunately.
