### ISSUE TITLE
Sopel quits with `Sopel is not running!` at startup if pid file is empty

### ISSUE THREAD

**Issue by ralienpp** [sopel-irc/sopel#1075]
Sopel starts, but it fails with this error and the process quits.

I have poked around, attempting to figure out what was going on, and was able to reproduce this behaviour by doing the following:

- run Sopel
- terminate it with `kill -9`
- clear the contents of its `.pid` file
- run Sopel again, and it fails with this error

The background story is that I am running it on an embedded system that may occasionally go through sudden power offs or reboots. I wrote my Sopel bot for it to be able to talk to my device through an alternative channel if my regular mechanism fails - but alas, this didn't work when I actually needed it.

Upon investigating the machine itself when I finally got my hands on it, I concluded this was related to the PID file and explored that vector.

My workaround is to simply run it as `rm /tmp/sopel-default.pid && sopel`, but my inner voice tells me there is a more elegant way. Prior to that I changed the location of the PID file to `/tmp`, guessing that perhaps it had something to do with that.

Having looked at the code, I did not see any comments that explain what the logic of handling the PID file is, but I am guessing there is an issue there. It correctly concludes that Sopel isn't running, but why does it decide to quit, instead of starting and updating the PID file?

**Comment by dgw** [comment]
It probably expects the `.pid` file to be missing, not empty.

I only see [two code paths](https://github.com/sopel-irc/sopel/blob/aa46f76443846246a9de7ed7804ce9a77285da3d/sopel/run_script.py#L186-L192) where that error is printed. Probably something to do with `old_pid` being `None` if the file is empty.

**Comment by elad661** [comment]
yeah, the logic in line 186 is wrong. Someone, at some point, maybe when doing pep8 fixes probably, messed it up with parenthesis. it should only go in there when `opts.kill` or `opts.quit` are `True`, and not in every case where `old_pid` is `None`.

Our pidfile handling can certainly be smarter, regardless of that, like using `fcntl.flock()` with the `LOCK_EX`flag instead of manually checking if the a process with a matching pid is running (because Linux can recycle pids and give them to other processes).
