### ISSUE TITLE
wikipedia: may trigger other Sopel instances

### ISSUE THREAD

**Issue by maxpowa** [sopel-irc/sopel#1109]
Reported by `sloopy` in IRC. bot2-. uses prefix `.` and bot1-# uses `#`

```
<sloopy> .w Star Trek
<bot2-.> [WIKIPEDIA] Star Trek | "Star Trek is an American science fiction entertainment franchise created by Gene Roddenberry and owned by CBS and Paramount Pictures. The television series Star Trek: The Original Series, Star Trek: The Animated Series, Star Trek: The Next Generation, Star Trek: Deep Space Nine, Star Trek: Voyager, Star..." | https://en.wikipedia.org/wiki/Star_Trek
<bot1-#> [WIKIPEDIA] Star Trek | "Star Trek is an American science fiction entertainment franchise created by Gene Roddenberry and owned by CBS and Paramount Pictures. The television series Star Trek: The Original Series, Star Trek: The Animated Series, Star Trek: The Next Generation, Star Trek: Deep Space Nine, Star Trek: Voyager, Star..."
```

**Comment by psachin** [comment]
@maxpowa Any special scenario to re-produce this bug? I  don't see this behaviour. Am i missing something?

**Comment by maxpowa** [comment]
@psachin Running two instances of sopel with different prefixes in the same channel. The second bot is triggering on the URL that the first outputs. We prevent this in url.py but unfortunately have not in other modules that spit out urls.

**Comment by dgw** [comment]
Fixing this or not requires a decision on whether running multiple instances of Sopel in the same channel is a supported use case. I'm not sure it's worth adding code in various places to prevent one Sopel bot from triggering others, because there will always be other bot frameworks that would trigger anyway.

This sort of thing is best solved by adding all bots in a channel to each other's ignore/block lists, IMO.
