### ISSUE TITLE
Launching multiprocessing.Process from command

### ISSUE THREAD

**Issue by vladfi1** [sopel-irc/sopel#1176]
I have a module that looks like this:

```python
from sopel import module
from multiprocessing import Process

thread = None

@module.commands('start')
def start(bot, trigger):
    global thread
    thread = Process(...)
    thread.start()

@module.commands('stop')
def stop(bot, trigger):
    global thread
    thread.terminate()
```
However, when the `stop` command is activated the thread is not terminated, but instead it appears that sopel decides to shut down for some reason. In stdout I see:
```
Got quit signal, shutting down.
Calling shutdown for 0 modules.
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...

Welcome to Sopel. Loading modules...
```

**Comment by vladfi1** [comment]
It appears that subprocess.Popen also doesn't work - the `thread.terminate()` call does nothing.

**Comment by dgw** [comment]
Can confirm that Sopel itself receives the `SIGTERM` from calling `thread.terminate()` with this simple example (I passed `Process` a function that simply looped forever as its `target`).

Tested on current `master` (8ee37fc).

**Comment by dgw** [comment]
Confirming: Still happens on the `master` of today (d896391375545a9b9fb2e770cd1b61c29ec7c363).

**Comment by dgw** [comment]
Done some research and exploration. It doesn't look good for "fixing" this.

`Process.terminate()` sends `SIGTERM` (except on Windows), and Sopel interprets `SIGTERM` as one way of telling it to quit gracefully.

The question is, why does Sopel's main process receive the signal, and not the subprocess? It's probably because of how the subprocess is created—probably using `fork()`, which (per [the Python docs](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods)) "is problematic" in this case because Sopel is multithreaded.

So I'm not sure we can actually do anything about this. Newer versions of Python can use a new Python interpreter for the created subprocess instead of forking the parent, but this seems to have issues of its own when called from within a Sopel plugin.

I think the ultimate resolution of this problem might be, "Don't use `multiprocessing`." I feel like the doctor in that age-old joke… Or maybe the answer is, "Implement your own IPC and tell your subprocesses to terminate themselves when needed, instead of calling `terminate()`."
