### ISSUE TITLE
Multiple server/service authentication capabilities

### ISSUE THREAD

**Issue by UncleanlyCleric** [sopel-irc/sopel#1242]
I understand that this might be kind of an edge case for a few reasons, however... is it possible for Sopel to authenticate with multiple methods?

The IRC server I use has a server password set of lets say password1.
I am also trying to authenticate Sopel against an atheme nickserv with password2

[core]
...
auth_method = server
auth_password = password1

Obviously is what is allowing the bot to join the IRC server.  I know that I can't also add:
...
auth_method = nickserv
auth_password = password2

to the [core] section without causing the bot to crash out.  Is there any functionality for this, and I'm just missing it?

**Comment by dgw** [comment]
You're right about it being a bit of an edge case. Usually (in my experience, at least) an IRC server that requires a password will authenticate the user with that password as well, so separate login to services is not required.

As a workaround, you can run Sopel behind a bouncer (ZNC or similar) that can handle some or all of the authentication steps on Sopel's behalf.

Does anyone feel strongly either way about leaving this on the feature wishlist? The way authentication works could change in 7.0.0 to have different config values per method instead of reusing `auth_password` (for example) for multiple `auth_method`s.

**Comment by UncleanlyCleric** [comment]
I have zero issue waiting.  My question was more of a "is this already a thing?" question anyway.  Thanks!

**Comment by dgw** [comment]
Onto the wishlist it goes, then, to be worked on (hopefully) once all the outstanding quirks and bugs that crept in since the last real update are taken care of.

**Comment by HumorBaby** [comment]
Looks like #1513 is handling this.

**Comment by Exirel** [comment]
I think @HumorBaby is right. Since #1513 for Sopel 7, it is possible to authenticate a bot against a server auth AND a nick/user service, which should be good enough.

If someone wants even more than that, I believe that person could open a new issue for an even edgier edge case!
