### ISSUE TITLE
Bing is broken. Fix or remove?

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1290]
I don't know how long it's been since the Bing result function in `search.py` worked. But ~~it doesn't return anything now, and~~ the question is whether to ~~fix it or just~~ leave `.duck`/`.ddg`/`.g` as the only search provider in Sopel's core module set going forward.

From IRC I know that @Helldembez is in favor of just deleting it. I kind of want to keep it as an alternative provider (the idea being that if both DDG and Bing work, at least one of them will provide a result if the other makes a change that breaks the module). Anyone else have thoughts either way?

**Comment by dasu** [comment]
I was going to bring that up, it's an ez fix (change the regex from h3 to h2), the problem is that there is no .bing or whatever.  The only time bing function is called is when you run .search and that lists both bing and ddg results.  I personally would remove it since most of my users just .g whatever.

**Comment by dgw** [comment]
Yep, it's fixed but can still be removed later.

**Comment by dgw** [comment]
I'm going to close this question. The `.bing` command was added in 6.5.2, and it's not broken any more. Removing it can be brought up again in the future if someone really feels it's needed.
