### ISSUE TITLE
Python 2.7.x support threatened by IPython requirement

### ISSUE THREAD

**Issue by ralienpp** [sopel-irc/sopel#1308]
The current version of Sopel depends on `ipython` in its `requirements.txt`. This automatically pulls the latest greatest version of Ipython, which is 6.x. When installing that dependency, the following error occurs:

	Collecting ipython (from sopel)
	  Downloading ipython-6.3.0.tar.gz (5.1MB)
	    100% |████████████████████████████████| 5.1MB 48kB/s
	    Complete output from command python setup.py egg_info:

	    IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
	    When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
	    Beginning with IPython 6.0, Python 3.3 and above is required.

	    See IPython `README.rst` file for more information

Even if I install `ipython==5.0.0` before installing Sopel, it still downloads the latest version of IPython and attempts to install it.

If Sopel doesn't depend on some unique features of IPython that are not present in 5.x, I believe this can be addressed by setting the dependency to `ipython>=5.0.0`, and instructing Python 2.7.x users to install this version of IPython manually before installing Sopel itself.

**Comment by dgw** [comment]
Well, now, that's distressing. I tested on my own server (which runs Sopel under Python 2.7.3…yeah, it's that old) and `pip` gave me a compatible version of IPython. You can see where this was changed in #1263.

Sopel 6.5.3 will use conditional requirements based on `python_version`, as @alanhuang122 originally proposed before I did my (erroneous) `pip` test. Thank you for pointing this out, @ralienpp!

(Did I mention that I don't think `ipython` should be in the core module set? :grin: Honestly, it's pretty niche and it's the only module with weird dependency issues.)

**Comment by dgw** [comment]
For Sopel 7, I'm looking at pulling at least `ipython` and `spellcheck` into external modules. For more on that as it comes, follow #1291. The alternative idea bouncing around is making them installable extras, like how `requests` has the `security` option to install extra stuff for better SSL compatibility.

In your specific case, you might find [elad's old comment from #1037](https://github.com/sopel-irc/sopel/issues/1037#issuecomment-194445934) relevant. There are ways to install Python packages that don't enforce the dependencies, which you can use to avoid all the bloat of libenchant and/or IPython until Sopel itself makes those optional. If you're not using any of the core modules, you won't need their dependencies, so you can manually install only the stuff you absolutely need. (Don't quote me just yet, because I haven't been working on this project long enough to know _for sure_, but Sopel itself doesn't really need much at all outside the Python stdlib. Most/all of the deps in `requirements.txt` are for core module functions, not the actual IRC bot.)
