### ISSUE TITLE
[Bugzilla] Error calling shutdown method for module bugzilla:None

### ISSUE THREAD

**Issue by Helldembez** [sopel-irc/sopel#1320]
Noticed this in my logs. Bugzilla shutdown throwing none. On Sopel 6.5.3, Python 3.5.3.

```
Ping timeout reached after 120 seconds, closing connection
Calling shutdown for 2 modules.
calling reddit.shutdown
calling bugzilla.shutdown
Error calling shutdown method for module bugzilla:None
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...
 
Welcome to Sopel. Loading modules...
```

**Comment by dgw** [comment]
I noticed this the other day while testing things, too. Haven't looked into it yet, since it seems harmless… Thanks for the report though :smile_cat:

**Comment by dgw** [comment]
Actually it looks like a simple fix. The `url_callbacks` SopelMemory is never initialized if the bugzilla module isn't given any domains to look for (`setup()` returns without doing anything `if not bot.config.bugzilla.domains`), and then `shutdown()` tries to `del` a key from a nonexistent dict.

Self-assigning because I already found the problem. Just have to find a slightly longer window to properly write and test the patch. Maybe Wednesday. Certainly sometime later this week…
