### ISSUE TITLE
Sopel should keep track of its full hostmask

### ISSUE THREAD

**Issue by freeboson** [sopel-irc/sopel#1322]
Can we properly setup `Sopel.say()` to construct PRIVMSGs that will actually be at the 512 limit?

**Comment by dgw** [comment]
This is actually harder to do than it sounds. I'd like for Sopel to use the full line length available, too, but external factors can change an IRC user's hostname without notice: server-side mode changes, HostServ or similar being turned on/off, cloaking applied after NickServ authentication, etc.

Is there a reliable way to monitor for changes in one's own hostname that I'm unaware of? Happy to look into doing this if it's technically possible without a kludge like polling. :smile_cat:

As an aside, I've used multiple other IRC clients and frameworks that conservatively truncate (split) lines because they don't want to deal with tracking hostname changes either.

**Comment by dgw** [comment]
@kwaaak Why is that comment here? Make it in the relevant PR, make it on IRC, I don't care, just not on a random ticket that has nothing to do with any of what you're talking about. :confused:

**Comment by dgw** [comment]
Sopel tracks its hostmask as of #1537, but this is left open for the "512 limit" piece—that is, making Sopel actually use the stored hostmask to send as much as possible.

**Comment by deathbybandaid** [comment]
Just going to leave this here in regards to how many bytes the hostmask takes, and how many bytes it could portentially take as error handling.


````
        try:
            hostmaskbytes = len((bot.users.get(bot.nick).hostmask).encode('utf-8'))
        except AttributeError:
            hostmaskbytes = (len((bot.nick).encode('utf-8'))  # Bot's NICKLEN
                             + 1  # (! separator)
                             + len('~')  # (for the optional ~ in user)
                             + 9  # max username length
                             + 1  # (@ separator)
                             + 63  # <hostname> has a maximum length of 63 characters.
                             )
````

**Comment by dgw** [comment]
@deathbybandaid In 7.x we have `bot.hostmask`, FYI.
