### ISSUE TITLE
Sopel abuses log levels because of the default setting

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1337]
Modules like `ip.py` (which I noticed while reviewing #1336) use the wrong log level for some things because using the correct level would result in the log entry not getting printed by default. (That module spits out a `warning` when downloading the GeoIP database, which should be an `info` line, nothing more.)

Sopel's default log level should be changed to `INFO`, and modules that abuse `logger.warning()` or `logger.error()` should be corrected. This is probably going to be a Sopel 7 change.

**Comment by Exirel** [comment]
* I wanted to work on logging for a long time already
* it's issue number 1337. OF COURSE I have to work on it. :trollface:

**Comment by dgw** [comment]
One PR could theoretically close this, #1655, **and** #262 all at once, if done right. If you like turkey, or hat tricks, this could be your calling!

**Comment by Exirel** [comment]
So, Python logging can become quite complex, with a lot of flexibility, the possibility are endless. But as a result, the logging configuration can become a burden.

In order to make sense of it all, I think it's better to define a set of logger. From what already exist, I'd say to use these "loggers":

* `sopel.raw`: used to log raw event (in & out), do not propagate logs to `sopel` logger
* `sopel.error`: used to log error only, propagate to `sopel` logger which will do all the work
* `sopel`: log everything in the log file and the console output, and log errors only in the error file

Basically, that would lead to this kind of [dict configuration](https://docs.python.org/3.6/library/logging.config.html#configuration-dictionary-schema):

``` python
logging_config = {
    'version': 1,
    'loggers': {
        'sopel': {
            'level': 'INFO',
            'handlers': ['console', 'logfile', 'errorfile'],
        },
        'sopel.raw': {
            'level': 'DEBUG',
            'propagate': False,
            'handlers': ['console', 'raw'],
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
        'logfile': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'sopel.log',
            'when': 'midnight',
        },
        'errorfile': {
            'level': 'ERROR',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'error.log',
            'when': 'midnight',
        },
        'raw': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': 'raw.log',
            'when': 'midnight',
        },
    },
}
```

The main idea is that `sopel` is the "root" logger, and it uses handlers that are very selective:

* console output everything in the terminal, starting from DEBUG
* logfile output everything in the "sopel.log" file
* errorfile output errors only in the "error.log" file

Then you have `sopel.raw`, which does its own thing, by logging everything it get into a "raw.log" file, and it doesn't propagate to the `sopel` logger.

Also, instead of using file handler, I'd like to use rotating file handler.

@dgw what do you think? I'll try this out anyway, but I thought you might like to see the design concept before any PR.

**Comment by Exirel** [comment]
I just had a try (with an improved config), and I was able to replace the method "log_raw" with these 3 lines:

```
import logging
logger = logging.getLogger('sopel.raw')
logger.info('\t'.join([prefix, line.strip()]))
```

It nicely outputs on my console (something that we could prevent if we like), and in the raw log file.

Versus the current code, which is messy and open the file *every single time*, which I personally found total garbage:

```
if not os.path.isdir(self.config.core.logdir):
    try:
        os.mkdir(self.config.core.logdir)
    except Exception as e:
        stderr('There was a problem creating the logs directory.')
        stderr('%s %s' % (str(e.__class__), str(e)))
        stderr('Please fix this and then run Sopel again.')
        os._exit(1)
f = codecs.open(os.path.join(self.config.core.logdir, self.config.basename + '.raw.log'),
                'a', encoding='utf-8')
f.write(prefix + unicode(time.time()) + "\t")
temp = line.replace('\n', '')

f.write(temp)
f.write("\n")
f.close()
```
