### ISSUE TITLE
Configuration of Flood Protection

### ISSUE THREAD

**Issue by deathbybandaid** [sopel-irc/sopel#1342]
I think the Flood Protection should be configurable from the config file.

I have my bot behind ZNC for multiple reasons, and prefer the adjustability of it's flood protection, so the bot doesn't get kicked.

I think adding this to the core.config would be beneficial.

**Comment by dgw** [comment]
Not super high on the priority list right now, but a PR adding this would get a look.

**Comment by deathbybandaid** [comment]
Do you think any of this is still relevant/usable?

https://github.com/sopel-irc/sopel/pull/908/commits/f58fa9f938efc3af6cefec79e56b6ce9ec571ce1

**Comment by dgw** [comment]
As far as I can see from #908, that was probably left unmerged because Embolalia pushed back on having config settings, and then @larsks closed it when the conversation stalled.

If you want to use that commit as a starting point (presumably you've read through #908 already?), I can't think of a reason not to. I would just ask that you rebase f58fa9f onto current `master` to keep credit for that code around in the commit log (and fix the typos in the commit message while you're at it, seeing as @larsks fixed them in the top PR comment anyway).

Out of courtesy, I also pinged @larsks. I think it's nice to ask people before building on unfinished code.

**Comment by dgw** [comment]
This seems like a good feature to add in the next major version, so I've assigned it to the 7.0.0 milestone.

@deathbybandaid With no answer from @larsks in the last 5 months, I think it's safe for you to have at this if you're still interested in working on it.

**Comment by predakanga** [comment]
This feature is one of the last remaining roadblocks in un-forking our own copy of Sopel, so I thought I'd offer the patch myself.

**Comment by Exirel** [comment]
> so I thought I'd offer the patch myself.

Oh, that's lovely, thank you! :heart: In one way or another, I hope Sopel 7 will be able to replace your fork, so you don't have to maintain it—I know how much time it can require!

**Comment by Exirel** [comment]
As I see it, #1518 fixed that (and the documentation is on its way).
