### ISSUE TITLE
Sopel v6.5.3's URL parser gets blocked for being a bot.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1391]
...
[12:20pm] <Ant>
          https://www.bloomberg.com/news/features/2018-10-04/the-big-hack-how-china-used-a-tiny-chip-to-infiltrate-america-s-top-companies
12:20PM <URL> [ Bloomberg - Are you a robot? ] - www.bloomberg.com
[12:21pm] <Ant> .version
12:21PM <URL> Ant: Sopel v. 6.5.3
[12:25pm] <Ant> https://www.bloomberg.com
12:25PM <URL> [ Bloomberg - Are you a robot? ] - www.bloomberg.com
...

Need to change its user agent to work?

**Comment by dgw** [comment]
I seriously doubt changing the UA string would help. Fetching Bloomberg in `python3 -i` with the UA string from my desktop version of Chrome yielded the same error page.

This is likely to be a `WONTFIX` (really, `CANTFIX`) because I have no interest in playing a cat-and-mouse game with sites that wish to block bots. Short of pulling in something like `selenium` as a dependency and going 100% fake browser, there will always be some sites that block Sopel because its requests look bot-like. They are, because it is one.
