### ISSUE TITLE
Rewrite to use asyncio instead of asynchat

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1414]
Python's `asyncore` and `asynchat` modules are deprecated as of 3.6. The `asyncio` module was added in 3.4, and Sopel should probably be rewritten on top of that when Python 2.x support is dropped.

I don't think there's a specific timeline for that happening yet. Maybe whenever Python releases a stable version that no longer supports `asyncore` and `asynchat`, it'll be a good time to make Sopel require Python 3.4+. That probably won't happen for years to come, but I think it's good to get this on the radar.

No milestone until Python actually removes the modules. The next major release of Sopel after that happens will include this rewrite. (Anyone want to place bets on what the version number will be? :joy_cat:)

**Comment by dgw** [comment]
(I _totally_ didn't decide to open this issue because I noticed #1414 was the next number. Nope… /s)

**Comment by Exirel** [comment]
Some information about versions:

* `asyncio` was included in Py3.4 as a [previsional API](https://docs.python.org/3.5/glossary.html#term-provisional-api), and is stable since Py3.6 only (so no Py3.5 here),
* `asynchat` is deprecated since Py3.6
* Py3.4 last release might be around March 2019, that will be the last release for Py3.4,
* Py2.7 end of life is planned for January 2020

Looking at these dates, what I suggest is to:

* drop py2.7 and py3.4 support January 2020,
* keep asynchat until the drop of Py3.5 support,

and as a side note: I worked on a prototype of IRC bot using `asyncio`, and it isn't that complicated, but it requires careful planning and testing.

**Comment by Exirel** [comment]
With #1697 it will be possible to implement a different backend for `asyncio` - or any kind of backend. So all that's left to do now is to actually implement one!

**Comment by Exirel** [comment]
1. it's not only running, it's also running with SSL on!
2. ping timeout, server timeout, and signal handlers are all done!
3. I think I know how to, but that'll be for another issue, one day (maybe even Sopel 8.1 or 9?)
4. There is now a draft PR, see #2256
