### ISSUE TITLE
Can't install sopel in a venv Python 3

### ISSUE THREAD

**Issue by BakasuraRCE** [sopel-irc/sopel#1422]
OS: Arch Linux

When i try to install sopel in a venv on python 3.7 it always fails because this dependency:
```

Collecting pyenchant (from sopel)
  Using cached https://files.pythonhosted.org/packages/9e/54/04d88a59efa33fefb88133ceb638cdf754319030c28aadc5a379d82140ed/pyenchant-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-s7o4hwwj/pyenchant/setup.py", line 212, in <module>
        import enchant
      File "/tmp/pip-install-s7o4hwwj/pyenchant/enchant/__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "/tmp/pip-install-s7o4hwwj/pyenchant/enchant/_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.

```

I installed python-enchant in the OS, but still showing the message, when i install using `sudo pip3 install sopel`, all success

**Comment by dgw** [comment]
If you figured out how to fix this problem, leaving the solution here might be helpful for future users who run into the same problem. :smile_cat:

**Comment by Corwind** [comment]
This issue should still be opened as the problem has not been solved yet.
Pyenchant cannot install with pip because the project is not maintained anymore and it is not up to date with the name of the library.

So basically it is a pyenchant issue that affects sopel's installation process.

This [https://github.com/rfk/pyenchant/pull/128/commits](commit) fixes the issue but it still has to be merged into master.
