### ISSUE TITLE
Twitter module without API key

### ISSUE THREAD

**Issue by Glandos** [sopel-irc/sopel#1466]
I have coded a sopel module that fetch tweets from web pages. It also extract images URL to avoid clicking on `t.co` links everytime.
But it does not uses the API, so it might not be a good idea to list here publicly.

So here is my real question: do you need it? Or do you prefer to avoid it?

**Comment by dgw** [comment]
You should feel free to publish it yourself. Whether that's just a file in a GitHub repo, or a PyPI package (module template [here](https://github.com/sopel-irc/sopel-cookiecutter))—go ahead!

We are trying to slim down the set of modules that come preinstalled with Sopel, though. Bundling so many modules with the bot makes the maintenance process much harder, because when those modules break users don't really know how to get an updated version before the next release of Sopel. See #1291.

If you do publish your module, though, keep an eye on [sopel-irc/module-db](https://github.com/sopel-irc/module-db) around when Sopel 7 comes out. You'll be able to submit your keyless Twitter module for inclusion there, if you wish.
