### ISSUE TITLE
.dice denial of service

### ISSUE THREAD

**Issue by heyitsanthony** [sopel-irc/sopel#1550]
If I spam sopel with `.dice 0xff^0xff^0xff`, sopel's replies to arbitrary commands (e.g., .`version`)  become indefinitely delayed. 

.version: `Sopel v. 6.6.5 (Python 3.4.8) at commit: 824ae7484b9e04310079a27d4d6ec40edeafdfd1`

environment: gentoo, ran from source, no special configuration

logs: nothing relevant in the logs

**Comment by dgw** [comment]
Confirmed, thanks for the report. @HumorBaby is debugging as I type this.

**Comment by HumorBaby** [comment]
The culprit is the flooding penalty logic:
https://github.com/sopel-irc/sopel/blob/824ae7484b9e04310079a27d4d6ec40edeafdfd1/sopel/bot.py#L323-L328


 If the delay between rolls (technically, between `bot.say` calls) is >3 seconds, all is well. If `bot.say` is called more frequently than every 3 seconds, the flood penalty is tripped, and it is based on the last messaged received to be sent.

The DoS behavior described above does not need a spam of `.dice ...` calls. In fact, as long as `.dice ...` is called any time before 3 seconds after the last command (e.g., `.version`), the bot will essentially lock up.

Here is the crux of whats happening:
The result of `.dice 0xff^0xff^0xff` is a ~64kb string (of digits, of course). When a penalty is applied on the response to the aforementioned `.dice ...` call, `penalty = float(max(0, len(text) - 40)) / 70` evaluates to `penalty = 2235` seconds (~37 minutes). The thread will then sleep for the `wait = 0.8  + penalty` and the `sending` lock never gets released.

For most commands, this is not an issue, because `len(text) / 70 ~< 2` seconds, and so there is no major  lag. But here, because the text is not truncated, `len(text)` blows up the final `penalty`.

The same applies for #1551

**Comment by dgw** [comment]
Fixed for the upcoming 6.6.6 release.
