### ISSUE TITLE
admin: censor settings more appropriately

### ISSUE THREAD

**Issue by HumorBaby** [sopel-irc/sopel#1571]
`admin.py` can be used to display setting values. Some setting values "should not" be displayed (e.g., password, secret keys), however. 

Currently, the plugin censors any setting that `endswith()` "password". Other settings that may not exactly be passwords, but are just as valuable, should similarly be censored. What is the best option to catch settings that should be prevented from being displayed?

Current affected settings (not exhaustive):
- `core.auth_password`
- `github.client_key`
- `github.secret` (this together with `client_key` should _definitely_ not be revealed)

Is `"password" is in` better than `endswith("password")` (similar for "secret", etc...)? If there is a setting like `secret_key` or `password_for_site`, `endswith()` will obviously not censor those. While those examples may not be the best setting names, and can certainly be changed to meet the `endswith()` condition, there is no documentation (I think...) that suggests settings be named in such a way if this behavior is desired.

Also, should `core.owner` be able to view the setting value uncensored since this will be happening in privmsg anyway?

Finally, if a value is censored from a `core.admins` user, should they even be allowed to set it?

_Originally brought up by @dgw in https://github.com/sopel-irc/sopel/issues/1570#issuecomment-486738630_

**Comment by dgw** [comment]
Well, this got long…

----

Easy enough to build a `sensitive_keywords` (or whatever) list and then censor settings with:

```py
if any(word in setting_name for word in sensitive_keywords):
    value = "(censored)"
```

Though that is a naïve approach, and could falsely match a lot of non-sensitive setting names depending on what goes in the `sensitive_keywords` list. It would be a bit more robust to try and enforce word boundaries (`_` either before or after the keyword), but still not perfect—and like with the current implementation, it would need to be documented. There's nothing stopping module developers from using `onelongvaluename` except convention. (Actually, this has only convinced me that, whatever the eventual implementation, this censoring feature needs to be documented in the website's [configuration tutorial](https://github.com/sopel-irc/sopel.chat/blob/d81cbdc036453e597385ed8c66fdb512f4c84637/_tutorials/part-2-config-wizard-and-setup-functions.md).)

> Currently, the plugin censors any setting that `endswith()` "password".

Also "pass": https://github.com/sopel-irc/sopel/blob/39e3680db18c4bed9801d040f7486c655b95a9a0/sopel/modules/admin.py#L295

But this is just a minor detail. :stuck_out_tongue:

> * `github.client_key`

This setting doesn't exist. (Also a minor detail.) The `client_id` (which does) is effectively public information, since it's displayed in the URL when a user edits their connection to an OAuth application: `https://github.com/settings/connections/applications/client_id_here`.

> Also, should `core.owner` be able to view the setting value uncensored since this will be happening in privmsg anyway?

No. The point is to prevent sensitive setting values from being logged, either on the user's end (if their client has logging enabled) or the bot's end (if e.g. `raw_log` is turned on—as it was by default [until 6.6.0](https://sopel.chat/changelog/6.6.0/#core-changes)).

And even if we stop worrying about logging, it's never a good idea to make plaintext passwords recoverable from where they are stored. It's not even ideal that Sopel's config file stores passwords in plain text in the first place… (Might be another issue for you to write here, if you're interested. If FileZilla can encrypt its saved passwords, so can we! I'm thinking a `SecureAttribute` config type that gets overwritten with an encrypted version at config load… No, @dgw, stay on topic!)

> Finally, if a value is censored from a `core.admins` user, should they even be allowed to set it?

Initially, my answer was "of course", with the logic that even though you can't see the old password, if you need to change it you should be able to.

But then I kept thinking about those logging considerations just discussed above. If sending the current/old value is undesirable because it might be logged, setting a new value via IRC message probably should be, too. Here, as always, we encounter the age-old "security vs. UX" conundrum.

If Sopel was its own ircd, it could get around this the way BitlBee (for example) does, by supporting setting secret values via the `OPER` command… but we're not a server, we're a client. I don't know of any client-to-client messages that are exempt from logging. :frowning:

**Comment by dgw** [comment]
Milestoned to go with #1600, since that's probably the best way to implement this.

**Comment by dgw** [comment]
Looks like we'll be getting #1600 sooner than 8.x, in the form of #1879.

**Comment by Exirel** [comment]
As discussed on IRC, this one will be first before #1600, thanks to  #1879!
