### ISSUE TITLE
Consider switching from pytz to Pendulum

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1645]
The main reason I want to give [Pendulum](https://github.com/sdispater/pendulum) a chance is its performance. There's a pretty stunning benchmark graph in [this comparison](https://pendulum.eustace.io/blog/a-faster-alternative-to-pyz.html) (though it only goes up to Python 3.5).

Sopel does a fair bit of messing with `datetime` objects, and is likely to do even more in the future, so the speed improvements would be useful. I'm also really in favor of having all `datetime`s (or rather, `DateTime`s) be timezone-aware by default. The idea of [passing around](https://github.com/sopel-irc/sopel/blob/a0c567c09083414d20ad4f989012f80062d6d2fa/sopel/tools/time.py#L107) a "naive" `datetime` that doesn't know its own timezone is kinda silly.

**Comment by Exirel** [comment]
I don't see the point.

Passing around naive datetime is quite dumb indeed, and we shouldn't do that. However, all it means is that we should do X instead of Y. Replace "X" by "pytz with aware datetime" by "arrow with aware datetime" or "delorean with aware datetime" or "pendulum with aware datetime" instead of "doing nothing". So from my point of view, there is no difference regarding how we manage datetime.

However, I can see the issues that Pendulum brings:

* replace `datetime.datetime` object with Pendulum's `DateTime`
* make sure there is no conflict between them anywhere in the code
* make sure it works for SQLAlchemy and the database (see Pendulum's docs about that)
* yet another dependency to look at (note that `pytz` is stable since forever)

I had a look at the benchmark, and here what they say (emphasis is mine):

> Each benchmark was done for Python 2.7, PyPy and Python 3.5. timeit was used with the default of **1 million executions** per benchmark and the best of 3 repeats was picked.

And sure, pytz's code can take up to 60s, even 70s with Py3.5. But let's bring that back to our scale: each execution is like 0.0001s, ie. less than 0.1ms. Do we have 0.1ms to spare here and there? Hell yes! We don't do a lot of datetime manipulations, it doesn't cost us a lot.

So yeah, I'm not a huge fan. :-1:

**Comment by dgw** [comment]
OK, not thinking of all those potential issues probably came from writing this idea at 1am. (The original idea from my personal notes probably got added even later at night, so… 😁)

I'll leave this open a bit longer in case anyone else wants to weigh in (mostly other @sopel-irc/rockstars, but anyone is welcome), and follow up with a narrower proposal about eliminating naive `datetime`s from Sopel's code and discouraging their use in plugins.
