### ISSUE TITLE
Sopel v6.6.9's ddg command always shows duplicate results.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1662]
Example:

[10:27am] Ant> .ddg test
10:27AM URL> Ant: https://www.speedtest.net/
10:27AM URL> Ant: https://www.speedtest.net/
...
[10:32am] Ant> .version
10:32AM URL> Ant: Sopel v. 6.6.9

**Comment by antdude** [comment]
Oops, darn copy and paste and unable to edit my original post. Here's it is:

[10:27am] Ant> .ddg test
10:27AM URL> Ant: https://www.speedtest.net/
10:27AM URL> Ant: https://www.speedtest.net/
...
[10:32am] Ant> .version
10:32AM URL> Ant: Sopel v. 6.6.9

**Comment by dgw** [comment]
Something weird like duplicate plugin files is going on here. The stock Sopel instance in `#sopel` at freenode doesn't have this issue:

```
12:40:00 <+dgw>  .version
12:40:01 <Sopel>  dgw: Sopel v. 6.6.9
12:40:03 <+dgw>  .ddg test
12:40:04 <Sopel>  dgw: https://www.speedtest.net/
12:40:10 <+dgw>  ahem
```

**Comment by antdude** [comment]
Which files would that be?

**Comment by dgw** [comment]
One `search.py` in the Python package root (varies depending on your environment, so I can't tell you exactly where) and another similar or identical file with a different name (maybe `search2.py`?) in `.sopel/modules` or one of the `extras` directories that might be defined in your config.

Basically, there could be an extra file in any of a number of places, and I can't find it for you. No one can, because we don't have access to your system (nor should we).

**Comment by deathbybandaid** [comment]
I've seen where sopel can sometimes get installed in multiple locations because of multiple linux users (including root)

it's possible that it is loading from two spots

**Comment by antdude** [comment]
I have a bunch of them, but which ones do I uhh get rid of?

$ locate search.py
/home/ant/SopelPython3/lib/python3.4/site-packages/pip/_internal/commands/search.py
/home/ant/SopelPython3/lib/python3.4/site-packages/prompt_toolkit/search.py
/home/ant/SopelPython3/lib/python3.4/site-packages/prompt_toolkit/key_binding/bindings/search.py
/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/search.py
/usr/lib/python2.7/dist-packages/pip/commands/search.py
/usr/lib/python2.7/dist-packages/pip/commands/search.pyc
/usr/share/doc/python-xapian/examples/simplesearch.py

$ locate search2.py
/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/search2.py

**Comment by dgw** [comment]
`search2.py` isn't part of the `sopel` distribution and doesn't belong in that folder.

If you want to use it without duplicate command output, you must _at minimum_ put `exclude = search` into your config file. Ideally, you should move `search2.py` to the `modules` directory within Sopel's homedir, too, because it's a user module.

Or you can just delete `search2.py`, if you're fine with using the included module. (N.B.: dasu's `search2.py` hasn't been updated since 2017, if that's what you're using. Core `search.py` has been tweaked several times throughout the 6.6.x lifecycle.)

**Comment by antdude** [comment]
Thank you. Removing search2.py fixed it. :)
