### ISSUE TITLE
Ctrl-C fails while loading

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1705]
Maybe we didn't catch all the things in #1478 / #1527, or maybe changes since then regressed? At any rate, on current `master` (d896391375545a9b9fb2e770cd1b61c29ec7c363), pressing Ctrl-C while plugins are loading (before the bot has connected to IRC) prints out the "Got quit signal, shutting down" message—_but doesn't shut down_.

Once the bot has actually connected, Ctrl-C will stop it. It's just not currently possible to interrupt the startup sequence because, e.g., "Crap, I forgot to enable/update <x> plugin/config first!"

**Comment by Exirel** [comment]
The problem comes from the signal handlers: they assume the bot is connected, so all they do is send a `QUIT` message to the server and nothing more.

The solution (at least for this particular issue), is to register these handlers once the bot is connected, and to unregister them once the bot is disconnected.

**Comment by Exirel** [comment]
#1893 should fix that, provided #1890 is merged first. Ah, it feels good! :+1:
