### ISSUE TITLE
Need startup() function for modules

### ISSUE THREAD

**Issue by madfordmac** [sopel-irc/sopel#1785]
I wrote a module to control a physical gauge from chat. Communication with the gauge is via serial port. I keep a persistent socket object in bot memory because the gauge goes through an initialization routine each time the socket is opened. I currently call socket.close() in the shutdown() function but the only place I have to initialize the socket is in the setup() function. This causes a problem when I have a network hiccup as the bot closes the serial socket, but doesn't open it again when it reconnects.

Ok, I could test if the socket is open every time I try to write to it, but it seems like having a place to do things when you connect (as opposed to when you load the module) could be useful outside of my use case.

**Comment by Exirel** [comment]
@madfordmac Hi! Thanks for the report. Could you provide us with the version of Sopel you are using? We may have fixed that already in the future release (due end of December or January 2020), but if not, I think it's worth the time fixing it.

**Comment by madfordmac** [comment]
I am currently running 6.6.9.

**Comment by Exirel** [comment]
I just looked at the code in the master branch, for the upcoming 7.0.0 version due this month (or early January), and it appears that we fixed that problem. You can have a look at the new [run](https://github.com/sopel-irc/sopel/blob/master/sopel/cli/run.py#L49) function, in particular the beginning of the `while True` loop where the [bot is initialized and setup](https://github.com/sopel-irc/sopel/blob/master/sopel/cli/run.py#L69-L95).

So, that won't fix your problem for Sopel 6.x because this won't get new release (no 6.9.x nor 6.10.x planned), but at least when you upgrade, you know it's fixed.

**Comment by dgw** [comment]
This being a report against 6.6.9 explains it. A lot of stuff got rewritten since that release, including a bunch of fixes related to the order of operations at startup and shutdown, consistently running shutdown and setup functions on each disconnect/reconnect cycle, etc.—tons of lifecycle improvements.

@madfordmac If you would, please test your plugin code against the current `master` branch. We're almost positive this isn't an issue any more, but if it is we'd like to fix it before releasing 7.0!

@Exirel We didn't (and won't) have a 6.7.x or 6.8.x either. 😝

**Comment by Exirel** [comment]
@madfordmac any news on that? Were you able to upgrade to Sopel 7?

**Comment by dgw** [comment]
We can reopen this if it's still a problem, but we need @madfordmac to come back and tell us if so. 😸
