### ISSUE TITLE
ip: MaxMind GeoLite2 Changes

### ISSUE THREAD

**Issue by half-duplex** [sopel-irc/sopel#1796]
### Description
MaxMind appears to now require an account to download the GeoLite2 databases, which Sopel currently uses. The geolite.maxmind.com domain, where Sopel downloads the databases, no longer exists, which is causing tests to fail.

### Reproduction steps
1. Clone master
2. Run `./pytest_run.py -v sopel/modules/ip.py`
3. Observe `sopel/modules/ip.py::test_example_ip_0 FAILED`

### Expected behavior
Test passes

### Notes
There seems to be an API with a [python library](https://pypi.org/project/geoip2/), but that also requires an account.

**Comment by dgw** [comment]
[This](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/) (CCPA nonsense) is why. Would have been nice of them to give a bit more than 12 days' notice.

I'll find time to look over the license agreement and decide if we can reasonably ship a built-in key like the reddit plugin does, or if `ip` will have to become an external package due to being unusable without the bot admin signing up for an account.
