### ISSUE TITLE
Feature: Dependent plugins

### ISSUE THREAD

**Issue by deathbybandaid** [sopel-irc/sopel#1838]
Hopefully I can explain the concept of this idea well enough that everyone follows my train of thought.

Scenario A: a proxmox lxc needs to load after another one at boot, so you adjust the start/shutdown order of your containers.

Scenario B: a systemd service is dependent on mysql, so you adjust the service to start after mysql is ready.

Scenario C: a sopel dev writes 2 plugins. PluginB depends on PluginA having been loaded first. the sopel dev wants to make sure that PluginB won't load until PluginA is there/ready. What does the sopel dev do!?

This led me to three possible ways to implement this, in order of mildly-ok to freaking-awesome:

1) a config value `load_order=PluginA,PluginB` (then load other plugins)

2) Similar to A), we can somehow use integers to say PluginA is a "level 1" foundation plugin that can be used by other plugins.

3) Go the systemd route and allow plugins to specify dependencies somehow.

**Comment by dgw** [comment]
You can share common code easily enough, if you package it right. A Python module doesn't have to be a Sopel plugin in order to import it. But _if_ we were going to ship this feature, the only option I would ever consider out of that list is the third.

The first option puts proper configuration of loading order on the user, meaning we'd get a spike in questions about PluginX or PluginY not working properly.

Option 2 has most of the same challenges (mostly "how to retrieve the priority value?") as option 3, but it's much less intuitive.

Before we get too far into the weeds on this—since you said on IRC it was a "train-of-thought idea"—we should determine if there truly are any use cases for this, vs. just putting shared code in an importable Python module. For example, a helper function that does something with the bot's database only needs `bot` (or `bot.db`) passed to it as an argument. Import it into a Sopel plugin and pass it the object it needs, and it'll work. The module it comes from doesn't have to be a plugin itself.

**Comment by deathbybandaid** [comment]
Let's say PluginA has a `class` with a value set to `None` until it's setup procedure has done whatever it does.

Let's say PluginB needs that value during it's setup procedure, but that value can't be `None`.

This would just be a means of making sure PluginB can't load before PluginA.

**Comment by dgw** [comment]
I would call that a design issue with PluginB. Plugins shouldn't ever assume that _anything_ is available during `setup()`. Not other plugins, not the IRC connection, not even the bot's logging subsystem. All that's guaranteed to be available during a plugin's `setup()` call is the plugin itself, and the passed-in `bot` object (which is not guaranteed to be network-connected).

**Comment by deathbybandaid** [comment]
Or we'll say:

PluginA reads a separate config file from the `sopel.cfg` and puts that information into the `class`, and PluginB needs that info without reimporting that info

**Comment by RustyBower** [comment]
Would it make sense to have something on the sopel.cfg for a depends_on (similar to docker), and when the bot starts, it can check if another plugin has successfully loaded before attempting to load?

**Comment by dgw** [comment]
@deathbybandaid Still a design issue, IMO.

Any information that's meant to be shared between plugins should be placed in `bot.memory`. That's the only reason `bot.memory` exists. If a plugin really needs something that isn't present in memory yet, it can handle that on its own through whatever method (access the data dynamically at runtime, set a timer to try the relevant part of setup later, etc.).

The entire config is available through `bot.config`; it isn't loaded in sections as each plugin gets set up, but all at once before any plugins are even loaded.

@RustyBower Sopel isn't depending on anything. The suggestion/request is for individual Sopel _plugins_ to be able to depend on each other. Or am I not understanding your idea?

**Comment by RustyBower** [comment]
Each plugin has it's own section within the sopel.cfg. My suggestion is that we handle some sort of depends_on section in there to check/ensure any dependent plugins load before it during runtime, and error out on startup if that's not the case.

**Comment by deathbybandaid** [comment]
The way I envisioned it after talking with @Exirel earlier would be something similar to `setup()` and `shutdown()`,, that might also include potential other metadata as well.

(for the below, the function name doesn't matter as much as the idea)

````
def metadata():
    depends_on="PluginA"
````

If it's not in the plugin, then assume load order doesn't matter.

**Comment by dgw** [comment]
@RustyBower No dependency management should appear in the config file, at all. Not even if it's implemented as a (for example) `ListAttribute` with a default value of `FooPlugin,EggsPlugin`—the user shouldn't be able to _break_ it by messing with the config file either—in this case, by putting `depends_on = SpamPlugin` in the config instead.

Dependencies should _only_ be declarable by the plugin itself, if we implement this feature.

@deathbybandaid Yes, if this happens, a new plugin-global method name is probably how it would be implemented. But first we need to find a use case that no currently possible technique can solve. We need to be sure this feature is worth the time it would take to implement, given that making it work would require rewriting large portions of the loader and other systems.

**Comment by deathbybandaid** [comment]
I just have several plugins that rely on the same information, and this seems like it would be a good way to fix that.

What's interesting, is plugin load order doesn't always seem to be consistent alphanumerical even.

**Comment by dgw** [comment]
Plugin load order is non-deterministic. Each type of plugin is enumerated, then those lists are concatenated together with no sorting: https://github.com/sopel-irc/sopel/blob/c705f450e56b9ddded10226c640a607249e33710/sopel/plugins/__init__.py#L145-L167 @Exirel can speak more authoritatively as to why, because he was the one who wrote the current code, but I suspect it's for performance; we don't currently care about the order in which plugins load, so there's no reason to waste CPU cycles making sure the order is consistent.

As I said above, `bot.memory` is the intended API feature for sharing information between plugins. The design of the plugin system reflects the original idea (going back multiple project forks/renames) that plugins should only depend on the bot itself, and maybe some libraries, but never other plugins. Maybe if you give some concrete examples (rather than hypothetical "PluginA depends on PluginB" cases, as above), one of us can suggest an alternative approach that wouldn't require enforcing a plugin load order?

**Comment by dgw** [comment]
Absent any examples of situations where "pluginB needs information loaded by pluginA" but can't defer loading that info until it's first invoked (at which point ALL plugins are guaranteed to be loaded unless broken)… Basically, I still think a few well-placed `if not condition: return` blocks can solve just about any case.

Letting plugins specify load-time dependencies on other plugins opens us up to nonsense like circular dependency graphs. No thanks, lol 🙃

Thanks to Exi for reminding me that this issue still existed. Neat idea, still, but probably not worth the effort.
