### ISSUE TITLE
Test suite fails with many 'pkg_resources.DistributionNotFound' errors

### ISSUE THREAD

**Issue by Ikke** [sopel-irc/sopel#1846]
I'm maintaining the `sopel` package on Alpine Linux. When upgrading to version `7.0`, every test in the test suite is failing with the following error (filename differs per test):

```
ERROR sopel/__init__.py - pkg_resources.DistributionNotFound: The 'sopel' distribution was not found and is required by the application
```
How are you supposed to run the test suite without installing sopel first?

Here is how it's built / tested.
https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/sopel/APKBUILD#L39

**Comment by dgw** [comment]
I'd suggest looking at how our tests run on Travis-CI. That's all covered in `.travis.yml` and `Makefile`. @Exirel Why didn't we remove `pytest_run.py` yet?

Other notes based on skimming your package file:

* Sopel doesn't need ipython any more; that plugin is now external.
* We'd be happy to consider tpaste for inclusion in the mainline list of pastebin providers, instead of patching the Alpine package. Also note it can be submitted to sopel-irc/sopel-help (which will probably replace the current plugin eventually).

**Comment by Exirel** [comment]
Hi, I didn't know there was a package for Alpine, that looks great!

> How are you supposed to run the test suite without installing sopel first?

We don't: we install it, using `python setup.py develop` to do so.
However, I believe you can do that without installing, by generating the egg-info file, using `python setup.py sdist` first. I'm not sure, I need to try.

I've one question though: when is the check performed? Because right now, the test suite has a nasty side effect of calling external services (it calls HTTP online services), so it might not be suitable for user when they install it.

**Comment by Ikke** [comment]
> I'd suggest looking at how our tests run on Travis-CI. That's all covered in `.travis.yml` and `Makefile`. @Exirel Why didn't we remove `pytest_run.py` yet?

I did try to look at how you did it in CI, but that 
> 
> Other notes based on skimming your package file:
> 
>     * Sopel doesn't need ipython any more; that plugin is now external.

Good to know, will remove that

> 
>     * We'd be happy to consider tpaste for inclusion in the mainline list of pastebin providers, instead of patching the Alpine package. Also note it can be submitted to sopel-irc/sopel-help (which will probably replace the current plugin eventually).

I changed it to tpaste because the previous paste server went awol (before there were multiple). I just carried the patch forward. I'll guess I will make a request to include it.

> Hi, I didn't know there was a package for Alpine, that looks great!
> 
> > How are you supposed to run the test suite without installing sopel first?
> 
> We don't: we install it, using `python setup.py develop` to do so.
> However, I believe you can do that without installing, by generating the egg-info file, using `python setup.py sdist` first. I'm not sure, I need to try.

Ok, thanks, I'll see if I can get the test suite to work that way. The reason this is an issue is that we run the test suite just in the project root, before anything is even 'installed'.

> 
> I've one question though: when is the check performed? Because right now, the test suite has a nasty side effect of calling external services (it calls HTTP online services), so it might not be suitable for user when they install it.

This is run on the builders before the project is packaged. Alpine Linux is trying to run the available test suites for all packages to make sure everything is working as expected.

**Comment by dgw** [comment]
To @Exirel's point about side effects, there is a way to skip tests that depend on online services, by passing `--offline` to pytest.

**Comment by dgw** [comment]
Not sure why we left this open for so long. Feel free to continue discussing if there's more to say, but I'll close it as this isn't really an "issue" in the true sense.

**Comment by Ikke** [comment]
For anyone interested, I've solved it with this:

```sh
export PYTHONPATH="sopel-dist"
python3 setup.py develop --install-dir=sopel-dist --no-deps
python3 pytest_run.py sopel test
```

This will allow you to run the tests without installing anything system-wide.

**Comment by Exirel** [comment]
Oh, so you are making something very similar to how virtualenv works. Nice. :)
