### ISSUE TITLE
accuweather.com's links show "Access Denied" results.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1934]
### Description
accuweather.com's links show "Access Denied" results.

### Reproduction steps
Connect to a IRC room with an active Sopel running and have it parse accuweather.com links like:
[08:09pm] Ant> https://www.accuweather.com
08:09PM URL> [ Access Denied ] - www.accuweather.com
[08:10pm] Ant> http://www.accuweather.com
08:10PM URL> [ Access Denied ] - www.accuweather.com
[08:10pm] Ant> http://accuweather.com
08:10PM URL> [ Access Denied ] - accuweather.com

### Expected behavior
I should not get "Access Denied" results.

### Logs
I don't see any updated:
$ ls -all *.log
-rw-r--r-- 1 ant ant 18380 Sep  4 15:04 default.error.log
-rw-r--r-- 1 ant ant     0 Aug 10 22:30 default.exceptions.log
-rw-r--r-- 1 ant ant     0 Aug 10 22:30 default.raw.log
-rw-r--r-- 1 ant ant   180 Sep  7 12:21 default.sopel.log
-rw-r--r-- 1 ant ant  1239 Aug 23 09:55 stdio.log

### Environment
- Sopel `.version`: 7.0.6
- Sopel installed via: pip
- Python version: 3.4.2 (default, Oct  8 2014, 10:45:20)
- Operating system: Debian Jessie v8
- IRCd `/version`: ircd-ratbox-3.0.8(20121231_3-27427)

### Notes
I don't know if this issue is just my own ancient setup. I wanted to try an updated active Sopel bot in IRC like on irc.freenode.net's #sopel, but its topic said not to test. :(

Thank you for reading and hopefully answering. :)

**Comment by dgw** [comment]
@antdude Please stop filing issues for random websites whose titles Sopel can't fetch. The sites either don't send a `<title>` tag, send generic/incorrect text in the `<title>` tag, or (as in this case) simply block the IP address Sopel tried to connect from for some reason (probably because it's in a known datacenter range). Sopel can't do anything about it.

Fetching AccuWeather titles works fine from a test bot on my home connection, but returns "Access Denied" from my production Sopel bot and the channel bot @HumorBaby runs for #sopel on freenode. Clearly the code works fine, and AccuWeather is just blocking based on IP and/or other client attributes outside Sopel's control.
