### ISSUE TITLE
Expand @plugin.require_chanmsg to specify channels

### ISSUE THREAD

**Issue by xnaas** [sopel-irc/sopel#2082]
### The problem
Limiting commands to specific channels requires some or many if statements such as:

```py
if trigger.sender == "#nsfw":
```

### The solution
Chatlog:
```
<cottongin> <xnaas> Is there a better way to  have an entire plugin confined to one channel than putting an if in every command? [...] Hmm...I guess I see how it can be done with dgw's duel.py, for example https://github.com/xnaas/sopel-duel/blob/b864c7f91d862d6e035dd759bb34228482de4804/duel.py#L20-L31
14:11:57 <cottongin> looking real briefly at that, that'd maybe be a nice improvement for 8.0, add in an optional argument to `@plugin.require_chanmsg(chans=[])`
<cottongin> idk how difficult that'd be to implement
* xnaas salivates
<xnaas> 🤤
<+dgw> Probably not very hard
<+dgw> Make a feature request I guess
* xnaas opens a feature request issue?
<xnaas> 👏
<cottongin> 👍
<cottongin> it makes sense to me
```

Particular solution proposed by @cottongin is to have something like `@plugin.require_chanmsg(chans=[])` where you could specify channels a command is limited to.

### Alternatives
`if` statements for days.

### Notes
Sopel is da best. :)

**Comment by xnaas** [comment]
@Exirel said "no, get good." 🤪

**Comment by cottongin** [comment]
To elaborate (via `IRC`):

```
15:22:49 <+Exirel> Not going to expand require_chanmsg, but I know how to deal with that.
15:23:08 <+Exirel> It's just Python, btw.
...
18:02:26 <+Exirel> Haven't tested it, but you get the gist of it. https://www.irccloud.com/pastebin/O9zQUoiu/snippet_require_channel_from_settings.py
18:02:47 <+Exirel> cottongin: the problem is: how do you dynamically define the list of channels to allow?
18:03:00 <+Exirel> You can't do that at plugin import time, you have to do it at runtime only.
...
18:04:04 <+Exirel> But yeah, just as mal said: you can write your own decorator. I'd suggest to call it first (i.e. the closer to your function).
...
18:06:26 <+Exirel> But yeah, there is a rework that I've in mind, that will replace the `require_chanmsg` by something that simply add a function to be called at runtime.
18:06:36 <cottongin> 👍
18:06:39 <+Exirel> Adding as many function as one wish into a list, and the bot can call it.
18:06:47 <cottongin> that gets around your dynamic list
18:06:54 <+Exirel> And then, you can have your own decorator with a system that is clearly made for it.
18:06:58 <+mal> Exirel: like registering callbacks?
18:07:03 <cottongin> 👍
18:07:11 <+Exirel> With the added benefit that you can now document each privilege check, etc.
```

I don't think this needed to be closed but wanted to include the alternative (that perhaps will make it into a PR later on down the road)

**Comment by xnaas** [comment]
*reopens this specifically to make @cottongin happy...not that he wants to b-baka!*

**Comment by dgw** [comment]
_Yes, good, normalize people writing their own bespoke decorators. 😈_

**Comment by dgw** [comment]
A new argument to `@plugin.require_chanmsg` wouldn't be able to pull from the bot's settings, so this request—as written—is a non-starter. It simply wouldn't be flexible enough to make sense as a plugin API feature.

Using a custom decorator as suggested by @Exirel in the IRC conversation quoted above (sample code mirrored below in case IRCCloud's pastebin loses it someday) is objectively the best way to implement this; the channel name can be hard-coded, passed as an argument, _or_ pulled from settings depending on use case.

```py
import functools

from sopel import plugin


def my_plugin_require_channel(func):
    @functools.wraps(func)
    def decorated(bot, trigger):
        if trigger.sender not in bot.settings.your_section.your_channel_list:
            return
        return func(bot, trigger)
    return decorated


@plugin.command('command_name')
@plugin.require_chanmsg
@my_plugin_require_channel
def my_command(bot, trigger):
    bot.say('This is the good channel.')
```

Such a decorator provided as part of `sopel.plugin` would be quite complicated if it accounted for all the possibilities (passed-in channel name, passed-in channel list, channel name from settings, channel list from settings), and its usage would therefore also be complicated. Instead, I will put on my list to add a section in the ["Advanced Tips & Tricks" page](https://sopel.chat/docs/plugin/advanced.html) of our plugin developer docs about how to restrict certain plugin callables to specific channel(s).

_Reevaluating because this came up again on IRC today. Giving the idea some closure (puns!) seemed sensible._
