### ISSUE TITLE
translate plugin doesn't seem to accept some languages as a translation point

### ISSUE THREAD

**Issue by xnaas** [sopel-irc/sopel#2241]
### Description
Try to translate English to simplified Chinese:
> <~xnaas> .tr :en :zh-cn test
> \<Sackbot> xnaas: Language guessing failed, so try suggesting one!

The test is the same regardless of the casing of `CN`.

Just putting in simplified Chinese shows that it knows what zh-CN is:
>  <~xnaas> .tr 测试
> \<Sackbot> [translate] "test" (zh-CN to en, translate.google.com)

### Reproduction steps
See above.

### Expected behavior
The message to be translated.

### Logs
See above.

### Environment
- Sopel `.version`: v7.1.7
- Sopel installed via: pip
- Python version: 3.9.2
- Operating system: Debian 11
- IRCd `/version`: ergo-v2.8.0
- Relevant plugins: translate.py

### Notes
N/A

**Comment by dgw** [comment]
[`isalpha()`](https://docs.python.org/3/library/stdtypes.html#str.isalpha) rejects those langcodes because of the `-` character.

https://github.com/sopel-irc/sopel/blob/aecc6dbbf029572de512fcf2bacabfd6bae23f72/sopel/modules/translate.py#L160-L161

I regret to say that this function probably has to switch to regex in order to support these two (out of nearly 100 🙁) language codes that contain characters outside the Unicode "Letter" categories. Note that the lack of any way (that I've found) to get the list of supported language codes from the translation service without forcing people to create API credentials blocks both this and another feature I thought about trying to implement this week (eliminating the need for `:` before the language hints).

**Comment by xnaas** [comment]
*looks at the Reddit plugin* I know we all love regex! 😉

**Comment by dgw** [comment]
I call this fixed by #2242. Will be looking into the TODOs I left myself there for further improvements in 8.0, but _this_ bug is gone.

**Comment by xnaas** [comment]
Nice.
