### ISSUE TITLE
blacklist words in url titles

### ISSUE THREAD

**Issue by Loot-Fist** [sopel-irc/sopel#2296]
### Requested Feature

Sopel should be able to look for blacklisted words in a URL title and drop the title or display a message to the channel/user to prevent malicious abuse of URL titles.  ie) profanities, slurs, etc.

**Comment by dgw** [comment]
I don't like the precedent this would set. Today it's `url`'s title fetch, tomorrow it'll be `youtube` comments or `twitter` tweets. There are simply _too many_ Sopel functions (built-in or otherwise) that can output user-generated content.

IMO, users who post inappropriate (based on chanops' stated policies) content should be dealt with by channel moderation.

**Comment by RustyBower** [comment]
Just my 2c as well. If people are misusing/abusing the bot, it should be channel ops / admins to correct that behavior, either through warnings, bans, or some other punishment.
