### ISSUE TITLE
RFC: Make `trigger.sender` STATUSMSG changes non-breaking for 8.0

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#2445]
> This is now making me think pretty hard about the intuitiveness vs. Sopel 7.x's behavior, though. Let's consider making `trigger.sender` behave as it did before, with the status prefix included, but also properly support the `Identifier` interface for checks like `trigger.sender.is_nick()`.

— _Originally posted by @dgw in https://github.com/sopel-irc/sopel/pull/2441#discussion_r1161165708_

In #2441 we fixed a behavioral regression in `bot.say()` and friends in the `bot` wrapper passed to plugin callables, making them once again send to the same STATUSMSG prefix as the triggering message by default.

I'm wondering about the impact this might have on plugins that currently expect `trigger.sender` to include the STATUSMSG prefix, though. The obvious thing to make `Identifier`s "smarter" is adding an attribute for the STATUSMSG prefix. The default string interpretation of an `Identifier` with status prefix would be e.g. `+#channel` as before, so if it was used as a destination the behavior would match 7.x. Other smarty-pants stuff could be done, like hashing without the status prefix (for `channel in bot.channels`-alike checks, say) and ignoring the prefix when calculating the return value of `.is_nick()`.

The shared usage of that object type for both channels and nicknames, though, gives me pause. Plus we'd be overloading a lot of stuff and ultimately, still making breaking changes—just different ones.

Do any of these ideas sound _not_ crazy enough to consider implementing them? Or can we come to a confident consensus that the solution and behavior changes in #2441 are the best way to live up to Sopel's stated "simplicity" mantra?

**Comment by SnoopJ** [comment]
I'm inclined to say that adding the prefix as an attribute to `Identifier` is **not** appropriate, because it's not part of _the identifier itself_, but some additional data about _how_ to deliver a message to an identifier. [Some of the documentation `master`](https://github.com/sopel-irc/sopel/blob/bc5843bd26bfc17d3082bd704f09b4aa58ce1a50/sopel/trigger.py#L358-L359) does suggest that we currently think about this data as part of the identifier, but I find this interpretation confusing, because the meaning of the prefix is limited to particular commands.

The upshot of this pedantic distinction is that we don't have to worry about the fine-grained details of your "smarty-pants" behavior, because delivery metadata is not `Identifier`'s problem.

My intuition is that plugins depending on `trigger.sender` to contain prefix information are probably in the minority, and if they are sensitive to the details of the status prefix, we have made that available to them on the `Trigger`. It's a bummer that code changes will be necessary for those plugins, but it's a better option than trying to expand the scope of `Identifier` to care about this metadata.

**Comment by Exirel** [comment]
I was tempted to consider d's option, but in my mind, I think I was already thinking like @SnoopJ here.

So I agree with @SnoopJ on all points (and thank you a lot because you phrased that better than I could have!)

**Comment by dgw** [comment]
(Sparing y'all my own rambly thought process that I just typed up and then deleted. The tl;dr was "@SnoopJ is [the best kind of correct](https://i.kym-cdn.com/photos/images/original/000/909/991/48c.jpg) and we should leave this alone".)
