### ISSUE TITLE
version: output file modification date if no version info present for /plugins file

### ISSUE THREAD

**Issue by wkeiuluf** [sopel-irc/sopel#2542]
### Requested Feature

If a `myplugin.py` in `/plugins` doesn't have `__version__ = 'whatever'` present, perhaps we could fallback to displaying the modification date of the file?

e.g.:

> \<user\> .version myplugin
> \<bot\> [version] myplugin modified 2023-11-02 @ 01:54UTC

And the timestamp could follow whatever preference order of user's timezone/formatting desired. (prefer default, then user, then channel? something like that)

### Problems Solved

Better than:

> \<user\> .version myplugin
> \<bot\> [version] myplugin (unknown)

in my opinion.

### Alternatives

N/A

### Notes

For simplicity, I could understand just always using UTC and following [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by SnoopJ** [comment]
The modified time depends on the installation process, so that if I do a fresh install of `sopel-mastodon` today, I will get an mtime (and other `stat` times) for 1 Nov, but if someone installed it yesterday or installs it tomorrow, they can get 31 Oct or 2 Nov, even if we have _exactly the same plugin content_. I'm not even sure if this behavior is consistent across platforms, but one counterexample should suffice for my point.

-1 from me, I don't think the potential benefits outweigh the wrinkles, especially when there's an affordance for plugin authors to declare their version.

**Comment by dgw** [comment]
Oh boy are there a lot of wrinkles.

Logically this would live not in the `version` plugin, but in the `plugins.handlers.PyFilePlugin` class as an override of the `get_version()` method. That part isn't too bad, until you realize that a `PyFilePlugin` might also be a directory with an `__init__.py`. Then you really get into the question of "yeah, modification time, but _whose_ modification time?"

I'm also leaning toward "Just spend one line from your weekly line budget and write `__version__ = 'idk whatever'` someplace in your plugin file." As long as the value is (or can be converted to) a string, you're golden.

_For dirty-hack points, you can do `__version__ = os.path.getmtime(__file__)`. For supreme overkill dirty-hack points you can `getmtime()` and pass it (convert to a `datetime`) through `tools.time.format_time()` before assigning the result as `__version__`._
