### ISSUE TITLE
Quit after timeout from server

### ISSUE THREAD

**Issue by devtea** [sopel-irc/sopel#300]
I've run into an issue where the bot times out from the server (freenode) and on reconnecting, the bot will quit because it sees that the nick is still in use. A couple possible solutions would be to ghost the existing nick, or retry a finite number of times before disconnecting to give the server a chance to disconnect the nick.

**Comment by dgw** [comment]
I suspect this will be easier to implement with the IRC backend refactor.

**Comment by Exirel** [comment]
Thinking about some solutions:

* behind a config option to enable this behavior, use nickserv's ghost command when this case is detected; this would require other options to be configured (such as the `auth_*` options)
* a job that periodically check the availability of the bot's wanted nick (but maybe only if the ghost option is not set?)

The problems are:

* making sure `bot.nick` is always the relevant one
* nothing is using the nick from the config file instead of the `bot.nick`

**Comment by Exirel** [comment]
So far I didn't use a job at all, and instead relied on listening to the `QUIT` event. This can be seen in #1930.
