### ISSUE TITLE
Use GeoIP2 for ip.py

### ISSUE THREAD

**Issue by bui** [sopel-irc/sopel#346]
The [original GeoIP](http://dev.maxmind.com/geoip/legacy/geolite/) is now legacy, being replaced with [GeoIP2](http://dev.maxmind.com/geoip/geoip2/geolite2/).

The only library for GeoIP2 I found was MaxMind's own [geoip2](https://geoip2.readthedocs.org/en/latest/), which currently only supports the online service and not GeoLite databases, so we'll have to wait.

**Comment by dgw** [comment]
From the GeoLite2 info page:

> As of April 1, 2018, updated versions of the GeoLite Legacy databases will be available to [redistribution license customers](https://www.maxmind.com/en/geolite-commercial-redistribution-license) only, although anyone can continue to download the March 2018 GeoLite Legacy builds. On January 2, 2019, the last build will be removed from our website. GeoLite Legacy database users will need to switch to the [GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/) or [commercial GeoIP](https://www.maxmind.com/en/geoip2-services-and-databases) databases and update their integrations by January 2, 2019.

That puts this squarely in the stable of things that must be updated by the end of the year. Fortunately it's a short list of stuff to do (so far, at least).

Tentatively assigning this to @kwaaak based on expressed intent to fix this in #1033. But not formally (yet), because GitHub won't let me for some reason.

**Comment by dgw** [comment]
Since the only real hard deadline for getting 6.6.0 out is the end of this year, and that's basically the same time as when the GeoLite Legacy databases will completely disappear, it's only fitting to (at least for now) stick this in the 6.6.0 milestone.

Also pinging @kwaaak to make sure this stays on the radar.

**Comment by kwaaak** [comment]
https://github.com/sopel-irc/sopel/pull/1336 😗

**Comment by dgw** [comment]
This should have been closed when #1336 was merged.
