### ISSUE TITLE
Improved API documentation & wiki migration

### ISSUE THREAD

**Issue by tyrope** [sopel-irc/sopel#398]
Wiki pages:
- [x] Installation & configuration.
- [x] Using plugin files. (Where to put them. Loading, reloading & unloading.) (#1923)
- [x] Reporting bugs. Where and how? (covered by website as of 2020-10-17)
- [x] Writing plugins (#1923)
  - Decorators (#311)
  - Defining Automated Tests (#353, can be part of Decorators)
  - Dealing with willie admins and/or channel ops, and when to use which (Access Control)
  - ~~Submitting your module to the main repo~~ (we no longer encourage this)

Suggestions welcome.

**Comment by dgw** [comment]
Retitled this issue to reflect the current state of thinking, which is that the wiki content should probably be migrated into the Sphinx docs. If it had been in `docs/` already, the old `willie` stuff would still be available in the docs for each release, instead of being deleted/moved when the project and its wiki pages were renamed. It's just better for future-proofing to keep all the docs in one place, IMO.

As mentioned in https://github.com/sopel-irc/sopel/issues/782#issuecomment-453785441, it's also (theoretically) easier to keep the config & core module docs up-to-date if they're part of the Sphinx build.

**Comment by Exirel** [comment]
I think it would be great, too, to ask Sopel's users what kind of information they wish to have in the documentation.

It doesn't mean this will be included in the doc, but at least that might help contributors to pick a topic to talk about.

**Comment by Exirel** [comment]
PR #1646 (merged into master for Sopel 7) is a great start to document properly Sopel's configuration options.

**Comment by dgw** [comment]
I checked off the install & config list item because of #1646 covering all the important core options, plus the overhaul of the install page that I did a while back in the website repo.

**Comment by dgw** [comment]
I'm punting the tutorial updates & new content to after 7.0. Spending time on those _before_ release is not a productive reason to delay.

**Comment by Exirel** [comment]
There is an improvement available in #1923 in particular around the usage of decorators and in general the vocabulary and anatomy of plugins. I also feel like most of that is now covered by the website, but I may be wrong.

**Comment by dgw** [comment]
I'm going to call this done. Pretty much everything listed in the OP is either merged, handled by the website, or about to be merged.
