### ISSUE TITLE
[chanlogs](White/Black)listing channels

### ISSUE THREAD

**Issue by tyrope** [sopel-irc/sopel#488]
as @elad661 mentioned in [PR477](https://github.com/embolalia/willie/pull/477#issuecomment-38103176). Logs should be able to be turned off, or made optional via config.

creating a small command to change this during runtime shouldn't be too hard. (.chanlog on/off)

**Comment by maxpowa** [comment]
https://github.com/maxpowa/sopel-chanlogs2 supports toggling logging per-channel.

**Comment by Exirel** [comment]
That's an interesting feature! Maybe we should investigate how `sopel-chanlogs2` works, and see what can be done: integrate it into sopel's core, or take the repo under the sopel-irc github org, or maybe there is a better option.

**Comment by dgw** [comment]
How did I lose/miss this? No idea.

Anyway. Adopting the `chanlogs2` module under the Sopel org is not a bad idea (if @maxpowa agrees).

I'm going to close this issue, though. It's been irrelevant since the `chanlogs` module was removed in Sopel 6.0, and the desired functionality is available in `chanlogs2` whether or not we adopt its repo.
