### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by slamanna212** [sopel-irc/sopel#736]
This started popping up today, the bot is the only thing using that database!

```
Traceback (most recent call last):
  File "/home/TrollOP/willie/willie/bot.py", line 634, in call
    exit_code = func(willie, trigger)
  File "/home/TrollOP/willie/willie/modules/seen.py", line 50, in note
    bot.db.set_nick_value(trigger.nick, 'seen_timestamp', time.time())
  File "/home/TrollOP/willie/willie/db.py", line 150, in set_nick_value
    nick_id = self.get_nick_id(nick)
  File "/home/TrollOP/willie/willie/db.py", line 114, in get_nick_id
    [slug]).fetchone()
  File "/home/TrollOP/willie/willie/db.py", line 64, in execute
    return cur.execute(*args, **kwargs)
OperationalError: database is locked

Traceback (most recent call last):
  File "/home/TrollOP/willie/willie/bot.py", line 634, in call
    exit_code = func(willie, trigger)
  File "/home/TrollOP/willie/willie/modules/weather.py", line 129, in weather
    woeid = bot.db.get_nick_value(trigger.nick, 'woeid')
  File "/home/TrollOP/willie/willie/db.py", line 161, in get_nick_value
    [nick.lower(), key]
  File "/home/TrollOP/willie/willie/db.py", line 64, in execute
    return cur.execute(*args, **kwargs)
OperationalError: database is locked

Traceback (most recent call last):
  File "/home/TrollOP/willie/willie/bot.py", line 634, in call
    exit_code = func(willie, trigger)
  File "/home/TrollOP/willie/willie/modules/seen.py", line 50, in note
    bot.db.set_nick_value(trigger.nick, 'seen_timestamp', time.time())
  File "/home/TrollOP/willie/willie/db.py", line 152, in set_nick_value
    [nick_id, key, value])
  File "/home/TrollOP/willie/willie/db.py", line 64, in execute
    return cur.execute(*args, **kwargs)
OperationalError: database is locked
```

**Comment by tyrope** [comment]
The only thing I can think of that's causing this error is there's a process somewhere still holding a lock on the database. Did Willie crash and restart? Check your processes list (Ctrl+Shift+Del in windows, `ps` in linux.) for anything that might hold this lock.

If you can't find anything, restarting the machine will definitely unlock the database, but any changes the process made/is making might be lost.

**Comment by slamanna212** [comment]
Ive restarted the machine as well, the issue came back. Its intermittent so
its hard to pinpoint, il use the ps command next time it happens


On Fri, Feb 13, 2015 at 2:39 AM, Dimitri Molenaars <notifications@github.com

**Comment by embolalia** [comment]
This is probably because Willie makes excessive use of threading, and SQLite is a bit limited in its ability to handle threading. Since seen has a db access for all the things, it's probably doing too much. It'd probably be fixed by making seen unthreaded and changing the priority (probably to high, since some things might wait on web results before accessing the db, and we'd need seen to be done before then).

**Comment by robguderian** [comment]
I've experienced this with the 'seen' plugin when chat rooms are flooded
with messages, if you're looking to recreate.

**Comment by slamanna212** [comment]
Exact same thing happened to my today

**Comment by cerealcable** [comment]
I started writing a few plugins that make use of the sqlite database which is incredibly convenient from the view of a developing a plugin. However, with that said it seems that literally any additional things accessing the database tips it over the edge on how often the locking issue happens.

I'm essentially seeing it every few minutes on a particular channel this is used on entirely because I rewrote bucket (well, in progress of rewriting it) to be less terrible. Effectively that's causing a lot of queries against sqlite which really isn't well supported by the database in general.

Looks like the realistic solution is to add additional support for external databases which is something I'm going to look into providing. Sopel out the box doesn't do too many queries but the problem would be that other plugins probably don't realistically expect to use any type abstraction layer (ORM for instance) to make them friendly towards multiple backends.

**Comment by embolalia** [comment]
Doesn't fix != fix, github. gluh.

**Comment by deathbybandaid** [comment]
I am also experiencing this issue

**Comment by dgw** [comment]
I don't think they're necessarily related errors, @deathbybandaid, but some way to add MySQL/PostgreSQL support back (maybe as a module somehow?) would be quite welcome as a PR for 7.0.0, if you're up to it.

**Comment by deathbybandaid** [comment]
I've been considering looking at MySQL for this,,,, I really think that sqlite just can't handle the read/writes.

Was there a reason alt DB support was removed from the project (between Willie and Sopel)?

**Comment by cerealcable** [comment]
sqlite was never intended for concurrent access regardless. I'd recommend
an abstraction between the database and the code in sopel. Lots of ORMs
exist for this purpose.

**Comment by dgw** [comment]
An abstraction layer would be great, yes. Thank you for the input, @cerealcable!

@deathbybandaid I don't remember exactly, but I believe the reason was some combination of not wanting to support alternate DB engines and wanting to remove as many dependencies from the core API as possible. In short, it was about simplifying the installation process to remove any need to set up a database (since SQLite can just create itself with no user input). There's some discussion in #194. Especially relevant is embolalia's opinion on SQLite, namely, "Really, given the scale and nature of the data we're dealing with here, anything else is overkill".

But any other DB engine support was always intended to be "Patches Welcome", so go nuts! :smile_cat:

**Comment by cerealcable** [comment]
At one point I discussed about using sqlalchemy but got the hint that the
additional dependency wasn't going to be entertained, even though we could
default to sqlite. Is that still the case?

**Comment by dgw** [comment]
As a straight dependency, probably not. But the idea of package extras has already come up this week regarding IPython, so I'd say 7.0.0 could add SQLAlchemy as an optional dependency for users who want a higher-test database.

I don't think it's any secret (to people who were around at the time MySQL was dropped) that I wasn't happy with that decision, and I think removing support for "proper" RDBMS was a step backwards for Sopel's production reliability. I'd be happy to look at any database-related PRs for 7.x.

**Comment by cerealcable** [comment]
@dgw Could you explain the reasoning for not including a python library as a dependency? If its because you want no additional effort for users installing or upgrading, that can all be handled by default behavior and setuptools supports handling dependencies.

**Comment by dgw** [comment]
It's not really my reasoning, but OK.

The effort is not the reason, since pip (or whatever) would install the library automatically. It's just a principle of not installing things that aren't strictly required for any number of reasons from avoiding clutter on the system to minimizing any potential attack surface from unnecessary stuff. That's why it would be great to make RDBMS support an extra, installable if desired but not installed by default.

That said, I'm open to arguments in favor of just bundling everything.

**Comment by dgw** [comment]
Assuming #1446 goes through, this will be "solved" by encouraging users who see this error to switch from SQLite to something better equipped to handle threading/concurrency (e.g. MySQL).
