### ISSUE TITLE
Circular imports in core

### ISSUE THREAD

**Issue by texom512** [sopel-irc/sopel#804]
Hello,

If I try that:
>>> import willie.module
I get:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.3/dist-packages/willie/module.py", line 21, in <module>
    import willie.test_tools
  File "/usr/local/lib/python3.3/dist-packages/willie/test_tools.py", line 16, in <module>
    import willie.config
  File "/usr/local/lib/python3.3/dist-packages/willie/config.py", line 51, in <module>
    import willie.bot
  File "/usr/local/lib/python3.3/dist-packages/willie/bot.py", line 31, in <module>
    import willie.module as module
AttributeError: 'module' object has no attribute 'module'

I used Willie 5.3.0 with Python 3.3 and I installed it like this:
pip3 install willie

Thanks in advance!

**Comment by texom512** [comment]
I found a very awesome thing: it work if do like this:
import willie.bot
import willie.module

Why???

**Comment by embolalia** [comment]
There are some screwy circular imports going on in there (because a lot of that wasn't really designed so much as grown). Loading things in a certain order breaks the cycle. It should be fixed, but since the way the bot normally loads doesn't expose the bug, and a lot of the core code goes nicely with marinara and meatballs, nobody's bothered yet. I'll leave this open, since it is something we should fix.

**Comment by embolalia** [comment]
I *think* this is accidentally fixed in the 6.0 branch. There might be some more lurking about somewhere, and a lot are hidden in `run()`, so I'm going to leave this open.

**Comment by maxpowa** [comment]
Pretty sure this is resolved in 6.3.x since we haven't had any reports. Going to close this.
