### ISSUE TITLE
wikipedia: Use db rather than config to determine default language per channel

### ISSUE THREAD

**Issue by embolalia** [sopel-irc/sopel#827]

**Comment by dgw** [comment]
This is easy to do, and we should do it sooner rather than later so we can deprecate the config language value per channel during 7.x and remove it in 8.0 without the deprecation and removal being too close together. Next time I'm in the mood to work on something fairly simple, hopefully I'll remember this.

**Comment by Exirel** [comment]
With #1916 merged all that is left is to wait for Sopel 8 to remove this setting.
