### ISSUE TITLE
Jobs weird on reload?

### ISSUE THREAD

**Issue by embolalia** [sopel-irc/sopel#831]
5.x reload uses `bind_commands`, which [clears the queue](https://github.com/embolalia/willie/blob/5.x/willie/bot.py#L269). This (I think) cancels all the jobs, meaning all scheduled stuff probably breaks when any module is reloaded. The 6.0 branch doesn't do anything with jobs, so old versions of jobs keep running. I haven't verified this behavior, but it's probably the case.

**Comment by embolalia** [comment]
Tweaked so that this is no longer any worse than what previous versions had, so this no longer blocks 6.0 from being released. It's still not right, though, so I'm leaving it open.

**Comment by firerogue** [comment]
Might be a complicated fix, but what if we saved some sort of callback to every job a module sets up so that when the module is unloaded/reloaded we can kill it? add some function to the JobScheduler that takes a Job object (or the ID of said object, or some other unique indicator) and removes all instances of said job from the queue?

**Comment by Exirel** [comment]
Will be fixed in #1479.

**Comment by Exirel** [comment]
It was already fixed in 6.5.x (or was it 6.6.x?, @dgw will know) but not yet fully available in master.

**Comment by dgw** [comment]
> It was already fixed in 6.5.x (or was it 6.6.x?, @dgw will know) but not yet fully available in master.

Nope, 6.6.x still clears the whole queue:

https://github.com/sopel-irc/sopel/blob/684c0b48298618dac7234b759923726708cb28d1/sopel/bot.py#L219-L222

Nevertheless, it's fixed on master now with #1479 merged, so… yay.
