### ISSUE TITLE
"IndexError: list index out of range" from url.py on posting URLs

### ISSUE THREAD

**Issue by miggyb** [sopel-irc/sopel#838]
Hey guys. I'm getting this issue with url.py, whenever a URL is posted:

    <@miggyb> https://pypi.python.org/pypi/willie/5.4.0
    <WillieTest> IndexError: list index out of range (file "/usr/local/lib/python2.7/dist-packages/willie/modules/url.py", line 136, in title_auto)

It started happening after an upgrade to the latest version on git (don't remember what version I was running before), but now I'm getting it on major releases since 5.0 (5.0.0, 5.1.0, 5.1.1, 5.2.0, 5.3.0 and 5.4.0) as well as the current 5.4.0 version from pip.

I've started a new AWS instance running Debian jessie (8.1, amd64) and tested it on both Freenode and Canternet (InspIRCd-2.0), and the issue persists there. Here's the trace:

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/willie/bot.py", line 460, in call
        exit_code = func(willie, trigger)
      File "/usr/local/lib/python2.7/dist-packages/willie/modules/url.py", line 136, in title_auto
        bot.memory['last_seen_url'][trigger.sender] = urls[-1]
    IndexError: list index out of range

And here's all the packages installed, both from dpkg and pip: https://paste.ee/p/Ipaqq

I'm pretty stumped, but since it's a standalone, vanilla EC2 instance without anything private on it, I can give the devs SSH access if wanted.

**Comment by miggyb** [comment]
Additional info:

The config file seems to do something with this, setting `exclusion_char = None` under the [url] section is part of the issue.

There's also more debug info on launch: https://paste.ee/p/QlNmy

**Comment by calzoneman** [comment]
@miggyb Ok, I think I found the issue here.  `url_finder` has `exclusion_char` mixed into it using string formatting.  If you set `exclusion_char` to `None` in the config, it's actually becoming the string `'None'`.  Since the regex is expecting `exclusion_char` to be a single char, the regex is broken and hence no matches occur, and `urls` is an empty list, and trying to index an empty list gives an `IndexError`:

https://github.com/embolalia/willie/blob/8395decd1aebbccc1b5411276b12ac035b0c8602/willie/modules/url.py#L87-L88

```python
    url_finder = re.compile(r'(?u)(%s?(?:http|https|ftp)(?:://\S+))' %
                            (exclusion_char))
```

https://github.com/embolalia/willie/blob/8395decd1aebbccc1b5411276b12ac035b0c8602/willie/modules/url.py#L131-L133
```python
    urls = re.findall(url_finder, trigger)
    results = process_urls(bot, trigger, urls)
    bot.memory['last_seen_url'][trigger.sender] = urls[-1]
```

The way I see it, there isn't currently a way to disable the exclusion char (if you set it to an empty string, then willie will just assume the default of '!'), so if you really don't want one, I think you'll have to just set it to a single character that you don't care about.

**Comment by embolalia** [comment]
Please verify that this issue still exists in 6.0.0a5.

**Comment by embolalia** [comment]
With no comment in a few months, I'm going to assume this is resolved.
