### ISSUE TITLE
Make willie wait a short time before joining channels to apply vhost

### ISSUE THREAD

**Issue by psy** [sopel-irc/sopel#844]
Willie joins channels immediately after connecting so vhosts get applied after joining and willie rejoins the channel. This could be fixed if willie would wait a short time after connecting (at least until it is identified).

IIRC there was a similar issue but i cant find it anymore so sorry if this is a duplicate.

**Comment by embolalia** [comment]
There is no way to know when the bot is identified, because nickserv systems are all totally unstandardized. One option would be to identify with SASL or a server password, if the network supports it, which should probably mean you're identified immediately. Another would be to use [`throttle_join`](http://sopel.chat/6.0.0a1/docs/#willie.config.core_section.CoreSection.throttle_join) in the core config. It's not exactly a time delay, but it should solve the problem for the most part. Is this sufficient?

**Comment by psy** [comment]
Sorry for the late reply! I got it working using SASL, so that was the pivotal point. Thank you for pointing this out!
