### ISSUE TITLE
Module members with attributes named interval, rule, etc. confused for decorated functions

### ISSUE THREAD

**Issue by Zokormazo** [sopel-irc/sopel#859]
Modules with 'interval' config option don't work, they throw this error:

TypeError: 'ValidatedAttribute' object is not iterable (file "/home/julen/projects/sopel/sopel/bot.py", line 177, in register)

If i change the config option name to something else they work properle

Tryed with this to discard any other problem:

interval.py
import sopel
from sopel.config.types import ValidatedAttribute, StaticSection

class IntervalSection(StaticSection):
    interval = ValidatedAttribute('interval', default='5')

def configure(config):
    config.define_section('test', IntervalSection)
    config.test.configure_setting(
        'interval',
        'interval to work'
    )

def setup(bot=None):
    if not bot:
        return
    bot.config.define_section('test', IntervalSection)

**Comment by embolalia** [comment]
Having an interval attribute on anything callable in your module makes Sopel think it's a function it should call periodically; @interval basically just adds an interval attribute to a function. For now, you'll have to rename the attribute to something else (the actual setting in the config file can be the same, but the name of the attribute on the class has to be different).

Fixing this well is a bit difficult. I don't want to just add `and not isattribute(StaticSection)` to [the logic that finds those things](https://github.com/sopel-irc/sopel/blob/master/sopel/loader.py#L195-L214), because obviously this can still also happen to anything else in your module. (Honestly, I'm kind of surprised that this is the first time I've heard of it happening). It'll probably have to be reworking the decorators to use mangled attribute names, which would once and for all break backwards compatibility with the ancient versions, so there probably won't be a complete solution until at least 7.0.

**Comment by Exirel** [comment]
Just a quick note here: this kind of issues arise in part because there is no way to tell Sopel that "this is a module", and that "this isn't a module": no meta-data, no "ModuleConfig" object, etc. nothing!

As said by @embolia, as it is, it's not easy to fix, and I'm not sure it's something doable for 7.x release.
But that's something I wish to work on if I've the time.

**Comment by dgw** [comment]
Milestone assigned so we don't lose track of this.

**Comment by dgw** [comment]
As noted in my writeup for #1931, even an innocent-looking global variable containing an innocent-looking stdlib object can trigger this.

**Comment by Exirel** [comment]
When I wrote this in the doc for Sopel 7:

    Sopel identifies a callable as a rule when it has been decorated with any of
    these decorators from :mod:`sopel.plugin`

I didn't realize that I basically got the solution for this issue.

As a result, these decorators will add an attribute and set it to `True` to the decorated callable. Sopel won't collect objects without this attribute, and it has to be set to `True`.

So yeah, it'll be done for Sopel 7.1!
