### ISSUE TITLE
Have bot say/msg without trigger?

### ISSUE THREAD

**Issue by mannibis** [sopel-irc/sopel#918]
I know this may sound like an easy/stupid question, but how do I get the bot to say something in a channel, without a module? I would like to write a python script that outputs text to a channel on my own accord, without triggers, etc. I have seen some methods in the Sopel class, but no examples to get me started.

I'd like to execute this .py script from outside the modules directory. Is this even possible with Sopel?

**Comment by elad661** [comment]
Well, no, you can't do it without a module. If you want the bot to periodically say something, you need to build a module that uses an interval.

 If you want to tell your bot what to say from the console, see my comment [here](https://github.com/sopel-irc/sopel/issues/646#issuecomment-64136700) and embolalia's comment [here](https://github.com/sopel-irc/sopel/issues/805#issuecomment-102816297). 

In any case you'd need to build a module to do what you want. Generally speaking, if you need to send a one-off message to a channel, Sopel is way more complicated than what you want. Sopel is designed mainly as a long-running bot providing utility functions.

Since this has been discussed in the past a couple of times, I'm closing this issue. If you have any questions regarding my reply, feel free to ask even though the issue will be closed.
