### ISSUE TITLE
Bot quits with excess flood when typing .help

### ISSUE THREAD

**Issue by phixion** [sopel-irc/sopel#952]
I'm migrating to sopel and came accross this issue. Any way we can throttle large messages better? I believe it's different from ircnetwork to ircnetwork how you should set it. The bot quits when he's like half through sending out the commands in private message

Quakenet:

03:32 < Phixion> .help
03:32 < Willie6> Phixion: I'm sending you a list of my commands in a private message!
03:32 -!- Willie6 [bot@2a01:1e8:e100:82c2::2] has quit [Excess Flood]

**Comment by embolalia** [comment]
It looks like we're finally going to have to re-asses the arcane magic that handles rate limiting. It'd be nice if there's some standard for telling us our max rate, but I'm betting that's not the case. So it'll probably have to be more arcane magic. Is this on a public network we could connect to for testing?

**Comment by tyrope** [comment]
@embolalia From the original post: `Quakenet:`

**Comment by ridelore** [comment]
Exactly, been talking about QuakeNet here's the ircd's settings, seems it doesn't include the rate limits

05:21 -!- WHOX WALLCHOPS WALLVOICES USERIP CPRIVMSG CNOTICE SILENCE=15 MODES=6 MAXCHANNELS=20 MAXBANS=45 NICKLEN=15 are supported by this server
05:21 -!- MAXNICKLEN=15 TOPICLEN=250 AWAYLEN=160 KICKLEN=250 CHANNELLEN=200 MAXCHANNELLEN=200 CHANTYPES=#& PREFIX=(ov)@+ STATUSMSG=@+ CHANMODES=b,k,l,imnpstrDducCNMT CASEMAPPING=rfc1459 NETWORK=QuakeNet are supported by this server

**Comment by maxpowa** [comment]
Yeah that won't include the rate limits. You'll have to contact an admin on
the network to get an accurate answer.
On Dec 6, 2015 8:23 PM, "Phixion" <notifications@github.com> wrote:
>
> Exactly, been talking about QuakeNet here's the ircd's settings, seems it
doesn't include the rate limits
>
> 05:21 -!- WHOX WALLCHOPS WALLVOICES USERIP CPRIVMSG CNOTICE SILENCE=15
MODES=6 MAXCHANNELS=20 MAXBANS=45 NICKLEN=15 are supported by this server
> 05:21 -!- MAXNICKLEN=15 TOPICLEN=250 AWAYLEN=160 KICKLEN=250
CHANNELLEN=200 MAXCHANNELLEN=200 CHANTYPES=#& PREFIX=(ov)@+ STATUSMSG=@+
CHANMODES=b,k,l,imnpstrDducCNMT CASEMAPPING=rfc1459 NETWORK=QuakeNet are
supported by this server

**Comment by ridelore** [comment]
from quakenet staff, makes perfectly sense to me:

09:37 <@shroud> there's no "X messages per Y seconds" rate limit, however here's an easy way to send as many messages as possible that works with virtually all ircds (i.e., not just quakenet):
09:38 <@shroud> a) assume that you have a buffer size of 1024 bytes
09:38 <@shroud> b) send messages (and other commands) until you reach that (virtual) buffer's size
09:39 <@shroud> c) once you've reached the limit send an invalid command (e.g. BOTFLOODCHECK or whatever) and wait until you get the "no such command" RPL
09:39 <@shroud> d) when you get the RPL go back to step a and "unplug" your queue, i.e. by sending another 1024 bytes

**Comment by gunnarbeutner** [comment]
Btw, the RPL I was referring to is 421 (ERR_UNKNOWNCOMMAND):

       421    ERR_UNKNOWNCOMMAND
              "<command> :Unknown command"

         - Returned to a registered client to indicate that the
           command sent is unknown by the server.

**Comment by maxpowa** [comment]
Yeah, that still requires knowing the IRCd buffer, because if you don't
know that you'll still get kicked for excess flood.

**Comment by gunnarbeutner** [comment]
While that's true 512 - 1024 is a reasonably safe value that should work with virtually all ircds.

**Comment by maxpowa** [comment]
But remember not all IRCds limit by buffer values, some - like espernet for
example - limit simply by messages. Espernet's limit is 10/5 (10 messages
within 5 seconds, regaining 2 messages every second), with a 5 message
burst. These limits are regardless of message length - you could send 10
one character messages or 10 450 char messages and it would not care.

**Comment by embolalia** [comment]
The "easy" way @ridelore mentioned (I'm inferring from context that `shroud` in that comment is @gunnarbeutner?) wouldn't really be easy for Sopel, just given the way the sending and triggering is set up. Waiting on a reply to start sending again would require super convoluted logic, and I don't know that it could be done reliably. (And things that should work everywhere almost never do, because this is IRC and why would anything be reasonable.)

It looks like @elad661 made some [tweaks a while back](https://github.com/sopel-irc/sopel/commit/6a6edcaa22ec3bdf28420297449d6b1e2a7a9923). Changing the .7 back to a .8 makes it sometimes work on Quakenet, which is progress.

Currently, we are only limiting PRIVMSGes (and only when done with `bot.say`, for that matter). I think this is a good idea; we can hold off PRIVMSGes to wait on rate limits, but we don't want to hold back on say PING. But, the current scheme can't count those other messages into its limiting, which kinda restricts what we can do.

It sounds like there are two primary schemes under which limitation can happen: lines per second and bytes per second. Quakenet does bytes, Esper does lines, and from some totally unsourced poking around, it sounds like Freenode (which I think the logic was originally written for) is a bit of a hybrid, but is more or less on the 10/5 limit. I think the solution here will be to actually implement both checks. The one variable I don't know in this would be the time it takes to clear the buffer in the bytes model, and whether it clears all at once or in chunks per message (I'd assume the latter).

**Comment by maxpowa** [comment]
Another thing about this is that we're currently sleeping the thread when waiting to send the message, which isn't exactly ideal. We should probably consider some sort of message queuing while we're working on this topic, so modules can continue to execute rather than being blocked by a bot.say

**Comment by dgw** [comment]
`.help` no longer sends a long list of PRIVMSGs, so this issue is quite likely obsolete.
