### ISSUE TITLE
Add a check for LC_ALL problems

### ISSUE THREAD

**Issue by zoell** [sopel-irc/sopel#984]
On v6.1.1:

Error loading meetbot: 'ascii' codec can't decode byte 0xc2 in position 70: ordinal not in range(128) (../../../../../lib/python3.4/encodings/ascii.py:26)

Any idea why is this happening?

**Comment by zoell** [comment]
Solved. The issue is the © sign in the Copyright text.

**Comment by elad661** [comment]
No, that's not the issue, the issue is that your LC_ALL is set to C (or unset) and not a UTF8 locale, and that makes Python 3 do weird things when it comes to unicode.

See https://gist.github.com/Spindel/8b2f2b5bbba10c93ca18 for example.

Maybe we should add a check to the startup script to warn (or even prevent) a case when the locale is non-unicode, because that might cause a lot of problems with handling unicode text within the bot.

**Comment by embolalia** [comment]
I like the idea of having a check, because this `LC_ALL` thing is ridiculous, but I'm not sure where it should go, since this error could come up before actually running any code, if a non-ASCII character were added in the wrong file.

**Comment by embolalia** [comment]
@elad661: Are there any other `LC_ALL` values besides `C` we should check for?
